---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-forward-auth
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: traefik-forward-auth
      version: 2.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m

  dependsOn:
    - name: traefik
      namespace: networking

  values:
    image:
      repository: thomseddon/traefik-forward-auth
      tag: v2.2.0
      pullPolicy: IfNotPresent
    podAnnotations:
      secret.reloader.stakater.com/reload: traefik-forward-auth-secrets

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-sso@kubernetescrd"
        hosts:
          - host: "id.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "id.${SECRET_DOMAIN}"

    env:
      TZ: ${TZ}
      LOG_LEVEL: debug
      PROVIDERS_GOOGLE_CLIENT_ID:
        valueFrom:
          secretKeyRef:
            name: traefik-forward-auth-secrets
            key: CLIENT_ID
      PROVIDERS_GOOGLE_CLIENT_SECRET:
        valueFrom:
          secretKeyRef:
            name: traefik-forward-auth-secrets
            key: CLIENT_SECRET
      AUTH_HOST:
        valueFrom:
          secretKeyRef:
            name: traefik-forward-auth-secrets
            key: AUTH_HOST
      COOKIE_DOMAIN:
        valueFrom:
          secretKeyRef:
            name: traefik-forward-auth-secrets
            key: COOKIE_DOMAIN
      DOMAIN:
        valueFrom:
          secretKeyRef:
            name: traefik-forward-auth-secrets
            key: DOMAIN
      WHITELIST:
        valueFrom:
          secretKeyRef:
            name: traefik-forward-auth-secrets
            key: WHITELIST
      SECRET:
        valueFrom:
          secretKeyRef:
            name: traefik-forward-auth-secrets
            key: secret

    service:
      main:
        type: ClusterIP
        ports:
          http:
            port:
              4181
