apiVersion: v1
kind: Secret
metadata:
    name: traefik-forward-auth-secrets
    namespace: networking
stringData:
    AUTH_HOST: ENC[AES256_GCM,data:n+ugbDHdvfI8c8HV4UUCb+7qjw==,iv:Dpe/hRnXn6XTZks9Qbm8bYDeuFdysji0hlK9ZDYphro=,tag:D63v6gpGXx+JqWZbbN4NUg==,type:str]
    CLIENT_ID: ENC[AES256_GCM,data:/SmIADLIcAgK02W7G4ZCyL0qU020Z2UmyKuWglloeAQ+d38sspy+D9v4NkyJb1DTftHo3HwetWku5oxJkcJJswkbvv6UR7Y=,iv:IbKvSDLLLiiuipbeljlgal7Z3LxHjve6m6m42EuuzL0=,tag:Q1/8P+Up3d0BBa0Yg6TIOA==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:wVjl5ZLsbabPT9c51Kd5FM2cbnqvovz8,iv:MT+i9F7rQkIg/zZGtJEAarhOERSlBtuI8a+NFx653xw=,tag:G+URf+ixq0U4MXbH7mYJMA==,type:str]
    COOKIE_DOMAIN: ENC[AES256_GCM,data:KyHb7wh+uMNaKx/1MJ8MzA==,iv:sLWb+9ap83mr8jhQ172S6eeYwhCDUS7Unf11WSl4/Dw=,tag:5G9RH/cng/gX30gZr4+yZA==,type:str]
    DOMAIN: ENC[AES256_GCM,data:nLAnw+uxbQaUMhGE9YUozg==,iv:/bx3iulbqd8O00FUhgyyJBJZbpIJzOfx5jbxfAoO1+o=,tag:HpkAv1Q8MmzNj62DZbQ/aw==,type:str]
    DEFAULT_PROVIDER: ENC[AES256_GCM,data:fwYcqiZi,iv:TY9ZTp53N2NOllTy7kgCQitsT6dwwrl3W+nGPe+oGBE=,tag:zTYU2lN92x4oFrmI7BiO3A==,type:str]
    WHITELIST: ENC[AES256_GCM,data:yk4obFwol0kcN6Qf4xNSuzaBqWybEgLJEUuNjz4eXwlQdLh0yUMybQojxjmQ1gToTGXr4WRqI7W2SAE=,iv:zk9ZGN0T8FmnXBKx1dIUqpAxrTKHjwCH25trqhqSWM0=,tag:WZTLR+2hjLR/KT+lSEH5JQ==,type:str]
    secret: ENC[AES256_GCM,data:71dFHHDdwyN2twr95zig6VSTkEMdxKkWLfBuNX7JOobgjGPZ,iv:dQBfhdiZIbZuGJ6U12uCbXBnclfQKKGnxIXKfr1sZ3o=,tag:Kd1T+HmJLjau3QaaCVruTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146q3v4ent838axktd2jq49v48pctuhhmv49843wnmlygv8r2uyysjs8mfd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTzNHMXJBN1FEVnV6a1ZG
            b0dVQ2dCL25NVThocWlONTVOY1RFdlJYZkdjCmF6WG5iVDBKa1ZyRS8wMWtYdmJW
            M2ZjVkNDbS9NVFFxNE1rbFVvd1FwdlUKLS0tIGk2YmZJL0dsby8waTFFdDUwOENR
            enpuWm5OZHVwOGRoVFIxQjZ5OXdEVXcKSg8XVaqQXqOw00pmkUGu5SyfYD9Ed6oZ
            ZTkztFONYTa4Lmsj2+nTfiwV321DMNicdDHoFzc/yL/sLJGshg75tA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-21T17:24:00Z"
    mac: ENC[AES256_GCM,data:sgY1YkF1pAfgZbTmVrgkgBLyZVo5okurkNZCS7hPV2FP1qgcOBEox412ERkyN9TYHkHbA9Va9KgjTJSwWBkwvucP3y82q9sWNFlh2wWphAvl84AV4jIo4C/nuzGqF3xnMubGKazslCNHs0M8w4tp4LLJs+/fwwUd4tTJrz0zCC4=,iv:Ys6T9HKuIp5g/nRTP8iWd55VJ3yjebvhodCB847kfdQ=,tag:aacygjn/d2TF3IWuOHZrFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
