---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-data-v1
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block
