---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph

  values:
    controllers:
      main:
        annotations:
          backup.velero.io/backup-volumes: unifi
        containers:
          main:
            image:
              repository: jacobalberty/unifi
              tag: v7.5.176
              pullPolicy: IfNotPresent
            resources:
              requests:
                memory: 500M
                cpu: 15m
              limits:
                memory: 1390M
            env:
              RUNAS_UID0: "false"
              UNIFI_UID: "999"
              UNIFI_GID: "999"
              UNIFI_STDOUT: "true"
              JVM_INIT_HEAP_SIZE:
              JVN_MAX_HEAP_SIZE: 1024M
              TIMEZONE: "${TZ}"

    persistence:
      unifi:
        enabled: true
        existingClaim: unifi-data-v1

    ingress:
      main:
        enabled: true
        className: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "lan"
          cert-manager.io/cluster-issuer: "letsencrypt-production"

        hosts:
          - host: &host "unifi.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: https
        tls:
          - hosts:
              - *host
            secretName: "unifi-tls"

    service:
      main:
        enabled: true
        type: LoadBalancer
        externalIPs:
          - ${METALLB_UNIFI_ADDR}
        externalTrafficPolicy: Local
        ports:
          http:
            port: 12345
          https:
            port: 8443
            protocol: HTTPS
            primary: true
          controller:
            enabled: true
            port: 8080
            protocol: TCP
          portal-http:
            enabled: true
            port: 8880
            protocol: HTTP
          portal-https:
            enabled: true
            port: 8843
            protocol: HTTPS
          speedtest:
            enabled: true
            port: 6789
            protocol: TCP
          stun:
            enabled: true
            port: 3478
            protocol: UDP
          syslog:
            enabled: true
            port: 5514
            protocol: UDP
          discovery:
            enabled: true
            port: 10001
            protocol: UDP
