---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre-flux kustomizations (todo)
  - unifi
  - wildcard-certificate
  - error-pages
  # flux kustomizations
  - ./traefik/ks.yaml
