---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portainer
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: portainer
      version: "1.0.x"
      sourceRef:
        kind: HelmRepository
        name: portainer-charts
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: portainer/portainer-ce
      tag: latest
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: "axis-x-rotate-counterclockwise"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
        - host: "kportainer.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "kportainer.${SECRET_DOMAIN}"

    persistence:
      enabled: true
      size: "5Gi"
      storageClass: "ceph-block"
      volumeName: portainer
