---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 60m
  timeout: 15m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: loki
      version: 5.8.6
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system

  maxHistory: 5
  install:
    remediation:
      retries: 4
  upgrade:
    # disableWait: true # intended to be temporary
    timeout: 15m
    remediation:
      remediateLastFailure: true
  uninstall:
    keepHistory: false
  values:
    backend:
      replicas: 3
      persistence:
        storageClass: ceph-block
      extraVolumeMounts:
        - name: rules
          mountPath: /rules/fake
        - name: scratch
          mountPath: /tmp/scratch
      extraVolumes:
        - name: rules
          configMap:
            name: loki-alerting-rules
        - name: scratch
          emptyDir: {}

    write:
      replicas: 1
      persistence:
        size: 5Gi
        storageClass: ceph-block

    read:
      replicas: 1
      extraVolumeMounts:
        - name: loki-rules
          mountPath: /rules
        - name: loki-rules-tmp
          mountPath: /tmp/scratch
        - name: loki-tmp
          mountPath: /tmp/loki-tmp
      extraVolumes:
        - name: loki-rules
          emptyDir: {}
        - name: loki-rules-tmp
          emptyDir: {}
        - name: loki-tmp
          emptyDir: {}
      persistence:
        size: 5Gi
        storageClass: ceph-block

    gateway:
      enabled: true
      replicas: 3
      ingress:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/appName: "Loki"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
        hosts:
          - host: &host "loki.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: tls.loki
            hosts:
              - *host

    loki:
      storage_config:
        boltdb_shipper:
          active_index_directory: /var/loki/index
          cache_location: /var/loki/index_cache
          resync_interval: 5s
          shared_store: s3
      schemaConfig:
        configs:
          - from: "2022-01-11"
            store: boltdb-shipper
            object_store: s3
            schema: v12
            index:
              prefix: loki_index_
              period: 24h
      structuredConfig:
        analytics:
          reporting_enabled: false
        auth_enabled: false
        server:
          log_level: info
          http_listen_port: 3100
          grpc_listen_port: 9095
        memberlist:
          join_members:
            - loki-memberlist
        limits_config:
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h
          ingestion_rate_mb: 16
          ingestion_burst_size_mb: 24
        common:
          path_prefix: /var/loki
          replication_factor: 1
          storage:
            s3:
              bucketnames: loki
              endpoint: "nas02.${SECRET_DOMAIN}:9000"
              s3forcepathstyle: true
              insecure: true
          ring:
            kvstore:
              store: memberlist
        ruler:
          storage:
            type: local
            local:
              directory: /rules
          rule_path: /tmp/scratch
          enable_alertmanager_v2: true
          alertmanager_url: http://prometheus-alertmanager:9093
          ring:
            kvstore:
              store: memberlist
          enable_api: true
        distributor:
          ring:
            kvstore:
              store: memberlist
        compactor:
          working_directory: /var/loki/boltdb-shipper-compactor
          shared_store: s3
          compaction_interval: 5m
          retention_enabled: true
          retention_delete_delay: 2h
          retention_delete_worker_count: 150
        ingester:
          max_chunk_age: 1h
          lifecycler:
            ring:
              kvstore:
                store: memberlist
              replication_factor: 1
            final_sleep: 0s
          chunk_idle_period: 5m
          chunk_retain_period: 30s
    test:
      enabled: false

    monitoring:
      dashboards:
        enabled: true
        annotations:
          grafana_folder: loki
        labels:
          grafana_dashboard: "1"
      serviceMonitor:
        enabled: true
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
      lokiCanary:
        enabled: false
      rules:
        enabled: true
        alerting: true
      alerts:
        enabled: true

  valuesFrom:
    - kind: Secret
      name: loki-s3
      valuesKey: minio_access_key
      targetPath: loki.structuredConfig.common.storage.s3.access_key_id
      optional: false
    - kind: Secret
      name: loki-s3
      valuesKey: minio_secret_key
      targetPath: loki.structuredConfig.common.storage.s3.secret_access_key
      optional: false
