---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-agent
  namespace: system-upgrade
  labels:
    k3s-upgrade: agent
spec:
  # renovate: datasource=github-releases depName=k3s-io/k3s
  version: "v1.30.2+k3s1"
  serviceAccountName: system-upgrade
  concurrency: 1
  nodeSelector:
    matchExpressions:
      - {key: node-role.kubernetes.io/control-plane, operator: DoesNotExist}
  prepare:
    image: rancher/k3s-upgrade:v1.32.3-k3s1-amd64@sha256:8f82349641df5cae2a73e39985afb6d5f5028c3e3173453089ce0b84d024f041
    args: ["prepare", "k3s-server"]
  upgrade:
    image: rancher/k3s-upgrade:v1.32.3-k3s1-amd64@sha256:8f82349641df5cae2a73e39985afb6d5f5028c3e3173453089ce0b84d024f041
