---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-agent
  namespace: system-upgrade
  labels:
    k3s-upgrade: agent
spec:
  # renovate: datasource=github-releases depName=k3s-io/k3s
  version: "v1.30.2+k3s1"
  serviceAccountName: system-upgrade
  concurrency: 1
  nodeSelector:
    matchExpressions:
      - {key: node-role.kubernetes.io/control-plane, operator: DoesNotExist}
  prepare:
    image: rancher/k3s-upgrade:v1.32.1-k3s1-amd64@sha256:09735f4458dd41a8f6fef4a7f9df84ce96fae3323fdb77571963e7c2aee9f747
    args: ["prepare", "k3s-server"]
  upgrade:
    image: rancher/k3s-upgrade:v1.32.1-k3s1-amd64@sha256:09735f4458dd41a8f6fef4a7f9df84ce96fae3323fdb77571963e7c2aee9f747
