---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-server
  namespace: system-upgrade
spec:
  serviceAccountName: system-upgrade
  concurrency: 1
  cordon: true
  # renovate: datasource=github-releases depName=k3s-io/k3s
  version: "v1.29.3+k3s1"
  nodeSelector:
    matchExpressions:
      - {key: node-role.kubernetes.io/control-plane, operator: Exists}
  tolerations:
    - {effect: NoSchedule, operator: Exists}
    - {effect: NoExecute, operator: Exists}
    - {key: node-role.kubernetes.io/control-plane, effect: NoSchedule, operator: Exists}
    - {key: node-role.kubernetes.io/master, effect: NoSchedule, operator: Exists}
    - {key: node-role.kubernetes.io/etcd, effect: NoExecute, operator: Exists}
    - {key: CriticalAddonsOnly, operator: Exists}
  upgrade:
    image: rancher/k3s-upgrade@sha256:70a238fdf8da99b99fcdb835f8162c9176e8078c170f5d6f349d3b38c3bfed7b
