---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-server
  namespace: system-upgrade
spec:
  serviceAccountName: system-upgrade
  concurrency: 1
  cordon: true
  # renovate: datasource=github-releases depName=k3s-io/k3s
  version: "v1.30.2+k3s1"
  nodeSelector:
    matchExpressions:
      - {key: node-role.kubernetes.io/control-plane, operator: Exists}
  tolerations:
    - {effect: NoSchedule, operator: Exists}
    - {effect: NoExecute, operator: Exists}
    - {key: node-role.kubernetes.io/control-plane, effect: NoSchedule, operator: Exists}
    - {key: node-role.kubernetes.io/master, effect: NoSchedule, operator: Exists}
    - {key: node-role.kubernetes.io/etcd, effect: NoExecute, operator: Exists}
    - {key: CriticalAddonsOnly, operator: Exists}
  upgrade:
    image: rancher/k3s-upgrade:v1.31.1-k3s1-amd64@sha256:a5aa3a9ca8f2105b26044776096d395c3374f37d4b6615da8777297a4d361348
