---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.21.2
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    crds:
      create: true
    image:
      repository: ghcr.io/cloudnative-pg/cloudnative-pg
      pullPolicy: IfNotPresent
      tag: 1.23.0@sha256:14241bd7a986d19e1335b66b33ff471d5526cc55087586fa278dc9f64a3322c4

    config:
      data:
        INHERITED_ANNOTATIONS: kyverno.io/ignore
