---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: default
spec:
  allowedUses:
    - Workload
    - Tunnel
  blockSize: 26
  cidr: 10.42.0.0/16
  ipipMode: Never
  natOutgoing: true
  nodeSelector: all()
  vxlanMode: CrossSubnet
