---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: thanos
      version: 12.23.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m

  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring

  values:
    query:
      enabled: true
      replicaLabels:
        - replica
      dnsDiscovery:
        sidecarsService: prometheus-thanos-discovery
        sidecarsNamespace: monitoring
      ingress:
        enabled: true
        hostname: "thanos.${SECRET_DOMAIN}"
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-sso@kubernetescrd"
        tls: true

    objstoreConfig: |
      type: S3
      config:
        bucket: thanos
        endpoint: "nas02.${SECRET_DOMAIN}:9000"
        insecure: true
        access_key: "${SECRET_MINIO_THANOS_ACCESSKEY}"
        secret_key: "${SECRET_MINIO_THANOS_SECRETKEY}"

    bucketweb:
      enabled: true
      ingress:
        enabled: true
        hostname: "thanos-bucketweb.${SECRET_DOMAIN}"
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-sso@kubernetescrd"
        tls: true

    compactor:
      enabled: true
      persistence:
        enabled: false
      retentionResolutionRaw: 30d
      retentionResolution5m: 30d
      retentionResolution1h: 5y
      resources:
        requests:
          cpu: 15m
          memory: 256M
        limits:
          memory: 512M

    storegateway:
      enabled: true
      persistence:
        enabled: false

    ruler:
      enabled: false

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
