---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: immich
      version: 0.7.2
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
      interval: 5m

  maxHistory: 2
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  values:
    env:
      DB_HOSTNAME: "cluster-immich-rw"
      DB_PORT: "5432"
      DB_DATABASE_NAME: "immich"
      DB_USERNAME:
        secretKeyRef: {name: secret-immich, key: DB_USERNAME}
      DB_PASSWORD:
        secretKeyRef: {name: secret-immich, key: DB_PASSWORD}
      TZ: "${TZ}"
      LOG_LEVEL: "debug"

    image:
      # renovate: datasource=github-releases depName=immich-app/immich
      tag: v1.107.2

    immich:
      persistence:
        library:
          existingClaim: nfs-immich-pvc

    postgresql:
      # Postgres is provided by cnpg
      enabled: false

    machine-learning:
      enabled: true

    redis:
      enabled: true
      architecture: standalone
      master:
        persistence:
          enabled: false
          medium: Memory
      replica:
        persistence:
          enabled: false
          medium: Memory

    server:
      controller:
        replicas: 2
      persistence:
        externaldata:
          enabled: true
          existingClaim: nfs-legacyphotos-pvc
          globalMounts:
            - path: /externaldata
      envFrom:
        - secretRef:
            name: secret-immich
      ingress:
        main:
          enabled: true
          annotations:
            hajimari.io/enable: "true"
            hajimari.io/icon: "movie-play"
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
            traefik.ingress.kubernetes.io/router.middlewares: "networking-chain-immich@kubernetescrd"
            cert-manager.io/cluster-issuer: "letsencrypt-production"

          hosts:
            - host: &host "immich.${SECRET_DOMAIN}"
              paths:
                - path: /
          tls:
            - hosts:
                - *host
              secretName: "immich-tls"

    microservices:
      enabled: true
      controller:
        replicas: 2
      envFrom:
        - secretRef:
            name: secret-immich
      persistence:
        externaldata:
          enabled: true
          existingClaim: nfs-legacyphotos-pvc
          globalMounts:
            - path: /externaldata
