---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-legacyphotos-pv
  namespace: media
spec:
  storageClassName: immich
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${NFS_SERVER}"
    path: "/volume1/homes"
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-legacyphotos-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: immich
  resources:
    requests:
      storage: 1Mi
