---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: mosquitto
      version: 4.5.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m

  values:
    image:
      repository: eclipse-mosquitto
      tag: 2.0.14

    env:
      TZ: "${TZ}"

    service:
      main:
        type: LoadBalancer
        externalIPs:
          - ${METALLB_MOSQUITTO_ADDR}
        externalTrafficPolicy: Local

    persistence:
      data:
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClassName: ceph-block
      configinc:
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClassName: ceph-block

    resources:
      requests:
        cpu: 75m
        memory: 64Mi
      limits:
        memory: 128Mi
