---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://storage.googleapis.com/t3n-helm-charts
      chart: mosquitto
      version: 2.4.1
      sourceRef:
        kind: HelmRepository
        name: t3n-charts
        namespace: flux-system
      interval: 5m

  values:
    image:
      repository: eclipse-mosquitto
      tag: 2.0.15

    service:
      type: LoadBalancer
      loadBalancerIP: "${METALLB_MOSQUITTO_ADDR}"
      externalTrafficPolicy: Local

    config: |
     persistence true
     persistence_location /mosquitto/data/
     log_dest stdout
     allow_anonymous true
     listener 1883
     listener 9090
     protocol websockets

    monitoring:
      podMonitor:
        enabled: true
      sidecar:
        enabled: true

    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClassName: ceph-block

    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        memory: 128Mi
