---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: traefik
      namespace: networking

  values:
    controllers:
      jellyfin:
        annotations:
          backup.velero.io/backup-volumes: config
        containers:
          app:
            image:
              repository: jellyfin/jellyfin
              tag: 10.9.7@sha256:76930362d2c266e8f0b2f51f1c6b039a5207525d0e138a1cdbec870c66c34b0f
            env:
              TZ: "${TZ}"
              JELLYFIN_CACHE_DIR: "/config/cache"
            resources:
              requests:
                cpu: 1
                memory: 2Gi
              limits:
                cpu: 4
                memory: 12Gi


        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            supplementalGroups:
              - 44
              - 109
              - 100

    service:
      app:
        controller: jellyfin
        ports:
          http:
            port: 8096

    ingress:
      app:
        enabled: true
        className: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "movie-play"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host "jellyfin.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: "jellyfin-tls"

    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config-v1
        globalMounts:
          - path: /config
            readOnly: false
      media:
        enabled: true
        existingClaim: nfs-media-pvc
        globalMounts:
          - path: /media
            readOnly: true
      transcode:
        enabled: true
        type: emptyDir
        medium: Memory
        globalMounts:
          - path: /transcodes
            readOnly: false
