---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: jellyfin
      version: 9.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system

  dependsOn:
    - name: traefik
      namespace: networking

  values:
    image:
      repository: ghcr.io/k8s-at-home/jellyfin
      tag: v10.7.7

    env:
      TZ: "America/Toronto"
      JELLYFIN_CACHE_DIR: "/config/cache"

    podSecurityContext:
      supplementalGroups:
        - 44
        - 109
        - 100

        #    service:
        #      main:
        #        type: LoadBalancer
        #        externalIPs:
        #          - "${METALLB_JELLYFIN_ADDR}"
        #        externalTrafficPolicy: Local

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "movie-play"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "jellyfin.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "jellyfin.${SECRET_DOMAIN}"


    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config-v1
#      media:
#        enabled: true
#        type: custom
#        volumeSpec:
#          nfs:
#            server: "${NFS_SERVER}"
#            path: /mnt/user/media
#        mountPath: /media
      transcode:
        enabled: true
        type: emptyDir
        medium: Memory

    resources:
      requests:
        cpu: 1
        memory: 3Gi
      limits:
        memory: 4Gi
