---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: threadfin
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph

  values:
    controllers:
      threadfin:
        annotations:
          backup.velero.io/backup-volumes: config
        containers:
          app:
            image:
              repository: fyb3roptik/threadfin
              tag: 1.2.37@sha256:96122ab220e14b881cbd40d7f8c7b022e1f9c6ecfe05aca2ab801e0321dc0d61
            env:
              TZ: "${TZ}"
              THREADFIN_PORT: 34400
            resources:
              requests:
                cpu: 25m
                memory: 512Mi
              limits:
                cpu: 2
                memory: 12Gi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

    service:
      app:
        controller: threadfin
        ports:
          http:
            port: 34400

    ingress:
      threadfin:
        enabled: true
        className: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdi:arrow-decision"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host "threadfin.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: "threadfin-tls"

    persistence:
      config:
        enabled: true
        existingClaim: threadfin-config-v1
        globalMounts:
          - path: /home/threadfin/conf
            readOnly: false
