---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-prometheus-stack
  - grafana
  - thanos
  - botkube
  - loki
  - promtail
  - speedtest-exporter
  - snmp-exporter-switch-0
  - snmp-exporter-gw-0
  - snmp-exporter-idrac
  - synology-exporter-nas02
  - unifi-poller
    #  - portainer
