---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre-flux kustomizations (todo)
  - grafana
  - thanos
  - botkube
  - loki
  - exportarr
  - promtail
  - snmp-exporter-switch-0
  - snmp-exporter-gw-0
  - snmp-exporter-idrac
  - synology-exporter-nas02
  # flux kustomizations
  - ./kube-prometheus-stack/ks.yaml
  - ./prometheus-pve-exporter/ks.yaml
  - ./speedtest-exporter/ks.yaml
  - ./unifi-poller/ks.yaml
