apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:dDMYR4I7XLBy79hnq3yGd15LwFdGVlonb2ni+1hnbfvOhW/K2jmzB+ousKJss4BgJf3pAuAXcRfWPs/Fv4AhnEUqP3GgLqFpPbWzFmtcIq0H8XU/8fIAm0Y+Ekbmo8ttk7DLTvU5y3kkT72lJ729yt8grYbiTyv4,iv:WN6wfmTKv2DMUabjEhSdIaSOb4gHl+0uI3+vAaB9wQc=,tag:qVXVWvdN7KL3TRsOo09Mww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146q3v4ent838axktd2jq49v48pctuhhmv49843wnmlygv8r2uyysjs8mfd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRy9ybmtkaEU0YlVCcGdr
            TlRBaGJZZHRwK05YWHNQMm5RVXE5SjAzL2tvCmlJTWlJdms1MmlUMnJWSGw5ZXdi
            TEZHYlJ4M1I3YWhFcjgvdy81dlRKZ1kKLS0tIGRWNXlFaW1UMXEyYjZXUmxxdGxj
            KytxUWZDUHdVcm9mNGdmY0gweVlWQXcKiDS8qKHvGl5OiOtdb0KU0xGwM2l0uo7t
            j5scFx1oVMYki3kixetZOV5A+W+To3SzkfUuWX5fuJPVHch48dWMnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-24T19:16:24Z"
    mac: ENC[AES256_GCM,data:78nW8F/VWs24egVENc77InEROTJSNEclzWQl/cY61jfr/KVWBvF+qzukUyzXyUdbxLytnjKipAdIiyN86JwHnAx3Fz9LgWeOLOUZtegyn/FB0eviY8lsOE8xUDqxihBkAyjl/sysFqiRPJL6aoCJ4OAT9ScMpIY/Szrw7IhyKmk=,iv:NhjtLjbxNwYSkE/hCj4cYdZ7VpYOMRtU9c9jvOz8uaw=,tag:rMeR9o7CgVaqBbyOoSUIag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
