---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: unifi-poller
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      unifi-poller:
        containers:
          app:
            image:
              repository: ghcr.io/unpoller/unpoller
              tag: v2.11.2@sha256:73b39c0b3b8fa92aa82a7613d3486253ffbd8c057833b4621402a268159bf2a2
            env:
              TZ: "${TZ}"
              UP_UNIFI_DEFAULT_URL: "https://unifi.networking.svc.cluster.local:8443/"
              UP_UNIFI_DEFAULT_VERIFY_SSL: false
              UP_UNIFI_DEFAULT_SAVE_SITES: true
              UP_UNIFI_DEFAULT_SAVE_DPI: false
              UP_UNIFI_DEFAULT_SAVE_EVENTS: false
              UP_UNIFI_DEFAULT_SAVE_ALARMS: false
              UP_INFLUXDB_DISABLE: true
              UP_PROMETHEUS_DISABLE: false
              UP_PROMETHEUS_NAMESPACE: "unifipoller"
            envFrom: &envFrom
              - secretRef:
                  name: unifi-poller-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
    service:
      app:
        controller: unifi-poller
        ports:
          http:
            port: 9130
    serviceMonitor:
      app:
        serviceName: unifi-poller
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m # Unifi API only polls at 2m intervals
            scrapeTimeout: 10s
