---
kubernetes:
  vars:
    ansible_ssh_user: ansible
  children:
    master:
      hosts:
        knode1:
          ansible_host: 192.168.8.21
        knode2:
          ansible_host: 192.168.8.22
        knode3:
          ansible_host: 192.168.8.23
        kcluster1-leader1:
          ansible_host: 192.168.8.27
        kcluster1-leadertemp:
          ansible_host: 192.168.8.29
    worker:
      hosts:
        # knode4:
        #   ansible_host: 192.168.8.24
        #   rook_devices:
        #     - /dev/sdb
        knode5:
          ansible_host: 192.168.8.25
          rook_devices:
            - /dev/sdb
        knode6:
          ansible_host: 192.168.8.26
          rook_devices:
            - /dev/sdb
        kcluster1-worker1:
          ansible_host: 192.168.8.28
          rook_devices:
            - /dev/sdb
