---
kubernetes:
  children:
    master:
      hosts:
        knode1:
          ansible_host: 192.168.8.21
        knode2:
          ansible_host: 192.168.8.22
        knode3:
          ansible_host: 192.168.8.23
    worker:
      hosts:
        knode4:
          ansible_host: 192.168.8.24
        knode5:
          ansible_host: 192.168.8.25
        knode6:
          ansible_host: 192.168.8.26
