---
kubernetes:
  children:
    master:
      hosts:
        knode1:
          ansible_host: 192.168.8.21
          rook_devices:
            - /dev/sdb
        knode2:
          ansible_host: 192.168.8.22
          rook_devices:
            - /dev/sdb
        knode3:
          ansible_host: 192.168.8.23
          rook_devices:
            - /dev/sdb
    worker:
      hosts:
        knode4:
          ansible_host: 192.168.8.24
          rook_devices:
            - /dev/sdb
        knode5:
          ansible_host: 192.168.8.25
          rook_devices:
            - /dev/sdb
        knode6:
          ansible_host: 192.168.8.26
          rook_devices:
            - /dev/sdb
