---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome-config-v1
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-block
