---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esphome
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m
  # See https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
  values:
    image:
      repository: ghcr.io/esphome/esphome
      tag: 2023.10.6

    persistence:
      config:
        enabled: true
        existingClaim: esphome-config-v1

    podAnnotations:
      backup.velero.io/backup-volumes: config

    env:
      ESPHOME_DASHBOARD_USE_PING: "true"

    service:
      main:
        ports:
          http:
            port: 6052

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: simple-icons:esphome
          hajimari.io/info: Programs esphome devices
          hajimari.io/group: automation
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "esphome.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "{{ (index .Values.ingress.main.hosts 0).host }}"
            secretName: "tls.esphome"

    addons:
      codeserver:
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.18.0@sha256:29267847d68332a28d249bd5235715402b144a3903b921da0a1962173aef10b1
        enabled: true
        volumeMounts:
          - name: config
            mountPath: /config

        ingress:
          enabled: true
          ingressClassName: "traefik"
          annotations:
            hajimari.io/enable: "true"
            hajimari.io/icon: vscode-icons:file-type-vscode
            hajimari.io/info: Esphome editor
            hajimari.io/group: automation
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"

          hosts:
            - host: esphome-vscode.${SECRET_DOMAIN}
              paths:
                - path: /
                  pathType: Prefix

          tls:
            - hosts:
                - esphome-vscode.${SECRET_DOMAIN}
