---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esphome
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m
  # See https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
  values:
    controllers:
      main:
        annotations:
          backup.velero.io/backup-volumes: config
        containers:
          main:
            image:
              repository: ghcr.io/esphome/esphome
              tag: 2023.10.6
            env:
              ESPHOME_DASHBOARD_USE_PING: "true"
              TZ: "${TZ}"

    persistence:
      config:
        enabled: true
        existingClaim: esphome-config-v1
        globalMounts:
          - path: /config

    service:
      main:
        ports:
          http:
            port: 6052

    ingress:
      main:
        enabled: true
        className: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: simple-icons:esphome
          hajimari.io/info: Programs esphome devices
          hajimari.io/group: automation
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host "esphome.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: "tls.esphome"
