---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: youtubedl-material
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      chart: youtubedl-material
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m

  values:
    image:
      repository: tzahi12345/youtubedl-material
      tag: "4.2"
      pullPolicy: IfNotPresent

    env:
      TZ: "${TZ}"

    persistence:
      config:
        enabled: true
        existingClaim: youtubedl-material-config-v1
      audio:
        enabled: true
        existingClaim: nfs-youtubedl-audio-pvc
      subscriptions:
        enabled: true
        existingClaim: nfs-youtubedl-subscriptions-pvc
      users:
        enabled: true
        existingClaim: nfs-youtubedl-users-pvc
      video:
        enabled: true
        existingClaim: nfs-youtubedl-video-pvc

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: network-rfc1918-ips@kubernetescrd
        hosts:
          - host: "youtubedl.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - "youtubedl.${SECRET_DOMAIN}"

    resources:
      requests:
        memory: "128M"
      limits:
        memory: "512M"
