apiVersion: v1
kind: Secret
metadata:
    name: secret-cloudnative-pg-admin
stringData:
    username: ENC[AES256_GCM,data:bh3kZfkxkQ4=,iv:9zFpk0xIosu/E0mHpczbM7TaqJyU0O2CnyKtfrfMutw=,tag:dvH56o5HiWu+f2l8eosvIQ==,type:str]
    password: ENC[AES256_GCM,data:/tKHXp2jU9O/p4lb28ZvDGJk/9A=,iv:DqD4QN2TY+yVjGEs+d9Rn3RXn6q8lvdMGae7K4ufr+s=,tag:o5H04p4lV1Y4w4B39xaAzQ==,type:str]
    aws-access-key-id: ENC[AES256_GCM,data:w899vsrmZ8vq,iv:JZ992nQ6OT60YW2BXJzMiqADDQQTrXkCG1nR3deQOow=,tag:YQ8i99fVSklaeLp86UYZGw==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:Sw0+DTgbX6PHB95KH53LWYie4yY=,iv:xJyLmuylXncTz+XoxsS0VqW5RYwDq9EC7KcZHlBJ29E=,tag:0vhjBiAW0joPDPUyvZMeNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146q3v4ent838axktd2jq49v48pctuhhmv49843wnmlygv8r2uyysjs8mfd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwb3pzc0gxVUFFcVljUUhE
            NEtjNFJId3FZQWQxTGxhNDZ1RnJ5YUxKclZBCldMT0x6ZEQ1amJ2SHdOTC9hbFp5
            Y3hsK3h5VWJpSmVmZTYwZnZNUDFaRW8KLS0tIC90U09IRmFiRHkweENZQ2tMY3Zk
            TUkzY1gremtkZ0t2cWtQOGNxZ1MySDAKKzE0W6pB+UlMbgUQOPrEmCHDxDsHYkva
            JNpmGvVWeqCX+AosM8KQ/3D3G8j1uEr395B1JCoLC4CZcZ12to89Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-16T13:32:36Z"
    mac: ENC[AES256_GCM,data:fYaefjQ6DWop0e6geub/mF8jf1M5zCI6ex+fHgC7hFoFeUnJG+4+03E6nMguOh77wv9bDeaZaqDpPXgQHVLrUnXoDOco5npOERfB+kzmAxEFIORUnWLZMEIP/L362ZASkDqltlpiIR8X1GgiqS3HWY5XkLHifBqLIRNmuCBQxyY=,iv:Wwrht/oo80PijpOMJOkQ87WM9kBut0EEf/yrvpnJ1MY=,tag:PaWKbQrN6RrxWJ6pQPuRbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: secret-cloudnative-pg-user
stringData:
    username: ENC[AES256_GCM,data:vrFMdjtLzetLNRrTkqpmhOdLyhN6L3FBsUEIXQ==,iv:090SGbc3ypS0/LDg5GTrPnHuPAx6384cpm1KDybM2Vc=,tag:+dcepoTH66ir5TSSepZhlA==,type:str]
    password: ENC[AES256_GCM,data:KsGLk4MNG/sDX7l5lKa3o6amizI1upw6skKn2Q==,iv:INQQ1gv3l2nw7j+bWfUvaJyaE6PHZ7w9oDrDcKenLSY=,tag:eeDhpvdrRj9kl/UkfHLG/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146q3v4ent838axktd2jq49v48pctuhhmv49843wnmlygv8r2uyysjs8mfd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwb3pzc0gxVUFFcVljUUhE
            NEtjNFJId3FZQWQxTGxhNDZ1RnJ5YUxKclZBCldMT0x6ZEQ1amJ2SHdOTC9hbFp5
            Y3hsK3h5VWJpSmVmZTYwZnZNUDFaRW8KLS0tIC90U09IRmFiRHkweENZQ2tMY3Zk
            TUkzY1gremtkZ0t2cWtQOGNxZ1MySDAKKzE0W6pB+UlMbgUQOPrEmCHDxDsHYkva
            JNpmGvVWeqCX+AosM8KQ/3D3G8j1uEr395B1JCoLC4CZcZ12to89Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-16T13:32:36Z"
    mac: ENC[AES256_GCM,data:fYaefjQ6DWop0e6geub/mF8jf1M5zCI6ex+fHgC7hFoFeUnJG+4+03E6nMguOh77wv9bDeaZaqDpPXgQHVLrUnXoDOco5npOERfB+kzmAxEFIORUnWLZMEIP/L362ZASkDqltlpiIR8X1GgiqS3HWY5XkLHifBqLIRNmuCBQxyY=,iv:Wwrht/oo80PijpOMJOkQ87WM9kBut0EEf/yrvpnJ1MY=,tag:PaWKbQrN6RrxWJ6pQPuRbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
