---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-config-v1
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 1Gi
