---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  dependsOn:
    - name: traefik
      namespace: networking
    - name: rook-ceph-cluster
      namespace: rook-ceph

  values:
    controllers:
      main:
        annotations:
          backup.velero.io/backup-volumes: config
        containers:
          main:
            image:
              repository: ghcr.io/sct/overseerr
              tag: 1.33.2
            env:
              TZ: "${TZ}"
              LOG_LEVEL: "info"
            resources:
              requests:
                cpu: 250m
                memory: 100Mi
              limits:
                memory: 750Mi

    service:
      main:
        ports:
          http:
            port: 5055

    ingress:
      main:
        enabled: true
        className: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "movie-search"
          hajimari.io/appName: "Requests"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: "letsencrypt-production"

        hosts:
          - host: &host "requests.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - secretName: tls.overseerr
            hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: overseerr-config-v1
        globalMounts:
          - path: /app/config
