---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-homeassistant
  namespace: default
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:14.8-6
  inheritedMetadata:
    labels:
      kube-image-keeper.enix.io/image-caching-policy: ignore
  primaryUpdateStrategy: unsupervised
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      storageClassName: nfs-client
      volumeMode: Filesystem
      resources:
        requests:
          storage: 1Mi
  enableSuperuserAccess: true
  superuserSecret:
    name: cluster-homeassistant-superuser
# bootstrap:
#   recovery:
#     source: &previous-cluster postgres-v2
  bootstrap:
    initdb:
      database: homeassistant
      owner: homeassistant
      secret:
        name: cluster-homeassistant-app-user
  postgresql:
    parameters:
      max_connections: "600"
      shared_buffers: 512MB
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://pgbackup/
      endpointURL: "http://${NFS_SERVER}:9000"
      serverName: postgres-v3
      s3Credentials:
        accessKeyId:
          name: secret-cloudnative-pg-admin
          key: aws-access-key-id
        secretAccessKey:
          name: secret-cloudnative-pg-admin
          key: aws-secret-access-key
  # # Note: externalClusters is needed when recovering from an existing cnpg cluster
  # externalClusters:
  #   - name: *previous-cluster
  #     barmanObjectStore:
  #       wal:
  #         compression: bzip2
  #         maxParallel: 8
  #       destinationPath: s3://pgbackup/
  #       endpointURL: "http://${NFS_SERVER}:9000"
  #       s3Credentials:
  #         accessKeyId:
  #           name: secret-cloudnative-pg-admin
  #           key: aws-access-key-id
  #         secretAccessKey:
  #           name: secret-cloudnative-pg-admin
  #           key: aws-secret-access-key
