---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-immich
  namespace: default
spec:
  instances: 3
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:14.11-v0.2.0
  #imageName: ghcr.io/bo0tzz/cnpgvecto.rs:16.1-v0.1.11 # https://github.com/immich-app/immich/issues/5813
  primaryUpdateStrategy: unsupervised
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      storageClassName: nfs-client
      volumeMode: Filesystem
      resources:
        requests:
          storage: 1Gi
  superuserSecret:
    name: secret-cloudnative-pg-admin
  enableSuperuserAccess: true
  resources:
    requests:
      memory: 1Gi
    limits:
      memory: 2Gi
  bootstrap:
    initdb:
      database: immich
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS "vectors";
      owner: immich
      secret:
        name: secret-cloudnative-pg-user
      dataChecksums: true
      encoding: 'UTF8'
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
    parameters:
      max_connections: "600"
      shared_buffers: 512MB
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://pgbackup/immich
      endpointURL: "http://${NFS_SERVER}:9000"
      s3Credentials:
        accessKeyId:
          name: secret-cloudnative-pg-admin
          key: aws-access-key-id
        secretAccessKey:
          name: secret-cloudnative-pg-admin
          key: aws-secret-access-key
