apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-homeassistant.yaml
  - cluster-immich.yaml
  - secret-cloudnativepg.sops.yaml
  - secret-homeassistant.sops.yaml
  - prometheus-rule.yaml
  - scheduledbackup.yaml
