---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: pgbackup-immich
  namespace: default
spec:
  # daily, 2am UTC
  schedule: "0 0 2 * * *"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: cluster-immich
    namespace: media
