---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: error-pages
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  dependsOn:
    - name: traefik
      namespace: networking
  values:
    controllers:
      main:
        type: statefulset
        replicas: 3
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: ghcr.io/tarampampam/error-pages
              tag: 2.25.0
            nameOverride: error-pages
            env:
              TEMPLATE_NAME: i-said-random
            resources:
              requests:
                memory: 100Mi
                cpu: 100m
              limits:
                memory: 500Mi

        defaultPodOptions:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: app.kubernetes.io/name
                          operator: In
                          values:
                            - error-pages
                    topologyKey: kubernetes.io/hostname

    service:
      main:
        ports:
          http:
            port: 8080
