---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: error-pages
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  dependsOn:
    - name: traefik
      namespace: networking
  values:
    controllers:
      error-pages:
        type: statefulset
        replicas: 3
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/tarampampam/error-pages
              tag: 3.8.1@sha256:b8ded6f847df91075429cf79cb9491bfd7d96de69936555498a2ff0614e003e4
            nameOverride: error-pages
            env:
              TEMPLATE_NAME: shuffle
            resources:
              requests:
                memory: 100Mi
                cpu: 100m
              limits:
                memory: 500Mi

    defaultPodOptions:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - error-pages
                topologyKey: kubernetes.io/hostname

    service:
      app:
        controller: error-pages
        ports:
          http:
            port: 8080
