---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-aiml-pv-embeddings
  namespace: stable-diffusion-webui
spec:
  storageClassName: aiml-embeddings
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${NFS_SERVER}"
    path: "/volume5/AIML/shared-embeddings"
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-aiml-pvc-embeddings
  namespace: stable-diffusion-webui
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aiml-embeddings
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-aiml-pv-extensions
  namespace: stable-diffusion-webui
spec:
  storageClassName: aiml-extensions
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${NFS_SERVER}"
    path: "/volume5/AIML/shared-extensions"
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-aiml-pvc-extensions
  namespace: stable-diffusion-webui
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aiml-extensions
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-aiml-pv-models
  namespace: stable-diffusion-webui
spec:
  storageClassName: aiml-models
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${NFS_SERVER}"
    path: "/volume5/AIML/shared-models"
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-aiml-pvc-models
  namespace: stable-diffusion-webui
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aiml-models
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-aiml-pv-outputs
  namespace: stable-diffusion-webui
spec:
  storageClassName: aiml-outputs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${NFS_SERVER}"
    path: "/volume5/AIML/shared-outputs"
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-aiml-pvc-outputs
  namespace: stable-diffusion-webui
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aiml-outputs
  resources:
    requests:
      storage: 1Mi
