---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app synology-exporter-nas02
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: prometheus-snmp-exporter
      version: 5.5.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 5m
  values:
    fullnameOverride: *app
    nameOverride: *app
    extraArgs:
      - "--config.file=/config/snmp.yaml"
    extraConfigmapMounts:
      - name: *app
        mountPath: /config/snmp.yaml
        subPath: snmp.yaml
        configMap: synology-exporter-nas02
        readOnly: true
        defaultMode: 420
    serviceMonitor:
      enabled: true
      namespace: monitoring
      module:
        - synology
      auth:
        - public_v3
      params:
        - name: nas02
          target: "${NFS_SERVER}"
          interval: 30s
          scrapeTimeout: 30s
      path: /snmp
      relabelings:
        - sourceLabels: [__param_target]
          targetLabel: instance
