---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: synology-exporter-nas02
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: prometheus-snmp-exporter
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 5m
  values:
    fullnameOverride: synology-exporter-nas02
    nameOverride: synology-exporter-nas02
    extraArgs:
      - "--config.file=/config/snmp.yaml"
    extraConfigmapMounts:
      - name: synology-exporter-nas02
        mountPath: /config/snmp.yaml
        subPath: snmp.yaml
        configMap: synology-exporter-nas02
        readOnly: true
        defaultMode: 420
    serviceMonitor:
      enabled: true
      namespace: monitoring
      params:
        - module:
            - synology
          name: nas02
          target: "${NFS_SERVER}"
      path: /snmp
      scrapeInterval: 60s
      scrapeTimeout: 60s
      relabelings:
        - sourceLabels: [__param_target]
          targetLabel: instance
