apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    image:
      repository: ghcr.io/onedr0p/plex # {"$imagepolicy": "flux-system:plex:name"}
      tag: 1.31.0.6654-02189b09f
    env:
      TZ: "${TZ}"
      ADVERTISE_IP: "http://${METALLB_PLEX_ADDR}:32400/,https://plex.${SECRET_DOMAIN}:443/"
      ALLOWED_NETWORKS: "${PLEX_NOAUTH_NETWORKS}"
      PLEX_CLAIM: "${SECRET_PLEX_CLAIM}"
      # https://support.plex.tv/articles/201105343-advanced-hidden-server-settings/
      PLEX_PREFERENCE_1: "FriendlyName=Hampstead"
      PLEX_PREFERENCE_2: "BackgroundTranscodeLowPriority=1"
      PLEX_PREFERENCE_3: "ManualPortMappingMode=1"
      PLEX_PREFERENCE_4: "ManualPortMappingPort=${PLEX_EXTERNAL_PORT}"
      PLEX_PREFERENCE_5: "LanNetworksBandwidth=192.168.0.0/16,10.0.0.0/8"
      PLEX_PREFERENCE_6: "TranscoderTempDirectory=/tmp"
      PLEX_PREFERENCE_7: "GdmEnabled=1"
      # PLEX_PREFERENCE_8: "TranscoderH264BackgroundPreset=fast"

    podSecurityContext:
      runAsUser: 568 #plex
      runAsGroup: 568 #plex
      fsGroup: 568 #plex
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44 #video
        - 109 #plex
        - 100 #users

    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${METALLB_PLEX_ADDR}"
          metallb.universe.tf/allow-shared-ip: plex  #used for UDP, which i don't have on ATM
          traefik.ingress.kubernetes.io/service.serversscheme: https
        ports:
          http:
            port: 32400
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "plex"
          hajimari.io/appName: "Plex"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "plex.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "{{ (index .Values.ingress.main.hosts 0).host }}"
            secretName: "tls.plex"
    persistence:
      config:
        enabled: true
        storageClass: "local-path"
        accessMode: ReadWriteOnce
        size: 20Gi
      transcode:
        enabled: true
        type: emptyDir
        accessMode: ReadWriteOnce
        emptyDir:
          enabled: true
          sizeLimit: 10Gi
      tmp:
        enabled: true
        type: emptyDir
        medium: Memory
      nfs-media-pvc:
        enabled: true
        existingClaim: nfs-media-pvc
        mountPath: /Data
        readOnly: false
    podAnnotations:
      backup.velero.io/backup-volumes: config
    resources:
      requests:
        cpu: 100m
        memory: 1500Mi
      limits:
        memory: 9000Mi
