apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      main:
        annotations:
          backup.velero.io/backup-volumes: config
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/plex # {"$imagepolicy": "flux-system:plex:name"}
              tag: 1.31.0.6654-02189b09f
            env:
              TZ: "${TZ}"
              ADVERTISE_IP: "http://${METALLB_PLEX_ADDR}:32400/,https://plex.${SECRET_DOMAIN}:443/"
              ALLOWED_NETWORKS: "${PLEX_NOAUTH_NETWORKS}"
              PLEX_CLAIM: "${SECRET_PLEX_CLAIM}"
              # https://support.plex.tv/articles/201105343-advanced-hidden-server-settings/
              PLEX_PREFERENCE_1: "FriendlyName=Hampstead"
              PLEX_PREFERENCE_2: "BackgroundTranscodeLowPriority=1"
              PLEX_PREFERENCE_3: "ManualPortMappingMode=1"
              PLEX_PREFERENCE_4: "ManualPortMappingPort=${PLEX_EXTERNAL_PORT}"
              PLEX_PREFERENCE_5: "LanNetworksBandwidth=192.168.0.0/16,10.0.0.0/8"
              PLEX_PREFERENCE_6: "TranscoderTempDirectory=/tmp"
              PLEX_PREFERENCE_7: "GdmEnabled=1"
              # PLEX_PREFERENCE_8: "TranscoderH264BackgroundPreset=fast"
            resources:
              requests:
                cpu: 100m
                memory: 1500Mi
              limits:
                memory: 9000Mi
        pod:
          securityContext:
            runAsUser: 568 #plex
            runAsGroup: 568 #plex
            fsGroup: 568 #plex
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 44 #video
              - 109 #plex
              - 100 #users

    service:
      main:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${METALLB_PLEX_ADDR}"
          metallb.universe.tf/allow-shared-ip: plex  #used for UDP, which i don't have on ATM
          #traefik.ingress.kubernetes.io/service.serversscheme: https
        ports:
          http:
            port: 32400
    ingress:
      main:
        enabled: true
        className: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "plex"
          hajimari.io/appName: "Plex"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host "plex.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: "plex-tls"

    persistence:
      config:
        enabled: true
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 20Gi
        globalMounts:
          - path: /config
      transcode:
        enabled: true
        type: emptyDir
        emptyDir:
          enabled: true
          sizeLimit: 10Gi
      nfs-media-pvc:
        enabled: true
        existingClaim: nfs-media-pvc
        globalMounts:
          - path: /Data
            readOnly: false
