---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: sd-webui
    newName: ghcr.io/ebiiim/sd-webui
    newTag: 1.2.0@sha256:d59a17a3c83ac1ded53eb9e6f18be3a9001289ee6c1ee81611860dfde35b8fe9

namespace: stable-diffusion-webui


  # [BASES] Basic things.
  # PersistentVolumeClaim
  # - https://raw.githubusercontent.com/ebiiim/sd-webui-docker/v1.2.0/k8s/bases/pvc.yaml
  # - bases/pvc.yaml
  # StatefulSet
  # - https://raw.githubusercontent.com/ebiiim/sd-webui-docker/v1.2.0/k8s/bases/sts.yaml
  # Service
  # - https://raw.githubusercontent.com/ebiiim/sd-webui-docker/v1.2.0/k8s/bases/svc.yaml
  # Ingress (optional)
  # - https://raw.githubusercontent.com/ebiiim/sd-webui-docker/v1.2.0/k8s/bases/ing.yaml

  # [MODELS] Please install 1 or more models.
  # Stable Diffusion 1.5 (License: CreativeML Open RAIL-M)
  # Waifu Diffusion 1.5 beta2 (License: Fair AI Public License 1.0-SD)
resources:
  - bases/sts.yaml
  - bases/svc.yaml
  - bases/ing.yaml
  - models/install-sd15.yaml
  - models/install-wd15b2.yaml


  # [Ingress] To set ingressClassName and host name, uncomment the patch.

  # [StatefulSet] To set storageClassName for volume "datadir", uncomment the patch.
patches:
  - patch: |-
      - op: add
        path: /spec/ingressClassName
        value: traefik
      - op: replace
        path: /spec/rules/0/host
        value: "stable-diffusion.${SECRET_DOMAIN}"
    target:
      group: networking.k8s.io
      kind: Ingress
      name: stable-diffusion-webui
      version: v1
  - patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: ceph-block
    target:
      group: apps
      kind: StatefulSet
      name: stable-diffusion-webui
      version: v1
