---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m

  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: traefik
      namespace: networking

  values:
    image:
      repository: ghcr.io/onedr0p/radarr
      tag: 4.6.4.7568

    env:
      TZ: "${TZ}"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "movie-search"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-sso@kubernetescrd"
        hosts:
          - host: "radarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "radarr.${SECRET_DOMAIN}"
    api:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
      hosts:
        - host: "radarr.${SECRET_DOMAIN}"
          paths:
            - path: /api
              pathType: Prefix
      tls:
        - hosts:
            - "radarr.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: radarr-config-v1
      media:
        enabled: true
        readOnly: false
        existingClaim: nfs-media-pvc
        mountPath: /media

    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
    podAnnotations:
      backup.velero.io/backup-volumes: config
    resources:
      requests:
        cpu: "0.04"
        memory: "256M"
      limits:
        memory: "512M"
