---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 192.168.8.230-192.168.8.250
  METALLB_TRAEFIK_ADDR: 192.168.8.230
  METALLB_HOMEASSISTANT_ADDR: 192.168.8.231
