# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:O748jPnGyspGIHtR8lD7pg==,iv:81m7aA0nDeFk+Qw1gD98m8xl55liN8w1vI69E8FLVR0=,tag:cj6XHB2rncZg2VUvhZyfvQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:FfeBENjENof6E4S+NH/+4tHZMKARQPg8xeBtaxjv,iv:z5/xa1pZz41+9EDonh5ZvZ4tXniiWmfcRKHoAXOnTE4=,tag:85o6jpHt8FD12VPpxVe7Sw==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:6U2TtjOM5FF6wB8=,iv:QnhWKOJ+Nh290Hi6Qp+foyaDan6Dtg4kaTlk8n/FQ+g=,tag:Z/QsmYAAYuxji8+2Am0npA==,type:str]
    SECRET_ALERT_MANAGER_DISCORD_WEBOOK: ENC[AES256_GCM,data:yYl7MqnVASxWHb0ZLuwRFgcjkX2UFoSFgtthlD85+znkQOxYiRi2ZXCaVq7KDAkmn+uYgwCZ0flvts3nZkrJnNrboWZ9rlgoOv1ozMhEectDR1CPoKJ5KRaHaYev1rd2Jr8z+D+JnIWnIbZMonzSKjXtvlM9ofFn5Kt4,iv:uRUpCFLnTRhIJa0nUj7sQhnPv0bl0HQ5jCc8KF6Rxr0=,tag:5gR8kREIMZwON0bd/3dVwA==,type:str]
    SECRET_GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:KqM74rY2dvI9,iv:R8wiAK8nG8ix14DY72I2wxoDFgEhkbsqXb+4MPeq5E4=,tag:9PmmuV2gVlJ/l6PytgJ/nA==,type:str]
    SECRET_MINIO_THANOS_ACCESSKEY: ENC[AES256_GCM,data:bKvWFJlf+eRScygUogBKHaQ8KWk=,iv:H3OHpBsVvEGvYOQ1WvrNCQcSwtQzXcWeROExxMJ2ni4=,tag:nGdjqWt4ct5vnQmzsTn3AA==,type:str]
    SECRET_MINIO_THANOS_SECRETKEY: ENC[AES256_GCM,data:FgRnHAXP2I1Z0fvRNGkwRke/CUn2PmU6P8yK6sA6eCMmqw7b/OsDIg==,iv:N1Wh4tG62AlCjO2gby59nAZ7lMdoUDjPbIAbmohBTDE=,tag:SFUIl77LUZLQnwTkGbFObg==,type:str]
    SECRET_QBT_USER: ENC[AES256_GCM,data:ILKeYlk=,iv:maH/Srg2GlLcS23xSmfXDYYIXrX8xA6MKHTXEobedLI=,tag:CEKwoTAoyaCHgjfw+D7Msg==,type:str]
    SECRET_QBT_PASSWORD: ENC[AES256_GCM,data:5GrtVb1DkMoA,iv:S47+rRZzEuispp7GIMag4WCRi9bMLELbcc643neGNOg=,tag:ysUm25LtmClc9GE5mfSYFQ==,type:str]
    SECRET_VPN_GATEWAY_PORT: ENC[AES256_GCM,data:N35iVQs=,iv:F38K0aBkgJJc/e4ga6/Cwfz5wEEyYZQKB+xthVNdXyA=,tag:qdHqc7B0U1KKkYl5e/8yKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146q3v4ent838axktd2jq49v48pctuhhmv49843wnmlygv8r2uyysjs8mfd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Y2VHbU9IdnVxNm00RWtD
            OTlqNXB6RENTZTlYVWF3Q284U2VaRDdyVEM0CkZzYUNlK2o2SXRMaHhnRTFpM2Jr
            ZlhLaTNuMmdnOFQ2bDdaR3VBYitDRkUKLS0tIGJQRGlUNmo5NFFSL2NTbHl5N0Ns
            ZkVSc0VNd1o2b1cwUEZXVlN2cm1uZHcK9HSW0QaeFV05/NMA5PDQ9D7eg5qbumtX
            XpUKR1BsSenXrRG8Zl4ryG0FljHYDEMBPrrzrex6gpGHuqCr0wFuzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-10T16:18:29Z"
    mac: ENC[AES256_GCM,data:fEgAcgiLvh6toChjG+9NJOJjndXdGSJSxQRsYsL46MHIdIgRyk32rq2tuvaz8mmoG1bkwQXqFQDQJBMMSGoWxr/fTX/axP0zNg2iUZnQbDmYqDZmIePbL/JKMZgvefyf4JL0CnjF3Si30B8MHTVub6GIx6K2S01tm+nHQm9khVQ=,iv:HIMe4bU6rGswm2pdU1V/wnbsnq6dHD/Z43BJP65iDyc=,tag:xQY5uX46lXVZoMIM/03lMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
