# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:O748jPnGyspGIHtR8lD7pg==,iv:81m7aA0nDeFk+Qw1gD98m8xl55liN8w1vI69E8FLVR0=,tag:cj6XHB2rncZg2VUvhZyfvQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:FfeBENjENof6E4S+NH/+4tHZMKARQPg8xeBtaxjv,iv:z5/xa1pZz41+9EDonh5ZvZ4tXniiWmfcRKHoAXOnTE4=,tag:85o6jpHt8FD12VPpxVe7Sw==,type:str]
    NFS_SERVER: "10.0.0.58"
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146q3v4ent838axktd2jq49v48pctuhhmv49843wnmlygv8r2uyysjs8mfd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Y2VHbU9IdnVxNm00RWtD
            OTlqNXB6RENTZTlYVWF3Q284U2VaRDdyVEM0CkZzYUNlK2o2SXRMaHhnRTFpM2Jr
            ZlhLaTNuMmdnOFQ2bDdaR3VBYitDRkUKLS0tIGJQRGlUNmo5NFFSL2NTbHl5N0Ns
            ZkVSc0VNd1o2b1cwUEZXVlN2cm1uZHcK9HSW0QaeFV05/NMA5PDQ9D7eg5qbumtX
            XpUKR1BsSenXrRG8Zl4ryG0FljHYDEMBPrrzrex6gpGHuqCr0wFuzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-25T21:12:40Z"
    mac: ENC[AES256_GCM,data:T0/dN6+NzjPxotZMxGP84Bp/tJK+afJs01np+uH4wDzDm0PWNCo/Bg+HUkOT4HY6vVjQvGAjcszoKJrGOOS/VSUXUdKbfPbc4maEyKwGIbDaR5Ay5qlbKxRP/e38WiWt3OiHiK4WIxgiCzyUX1WWNWCMe685JbOr/HclJnbpsO8=,iv:7n/y+5kb6TxwFGinCOpLocAHxQmRG6IUMJ144gic8MY=,tag:BMjX89Wd9wVX+xv28+geHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
