---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-export-pv
  namespace: home
spec:
  storageClassName: paperless-export
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${NFS_SERVER}"
    path: "/volume1/paperless/export"
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-export-pvc
  namespace: home
spec:
  storageClassName: paperless-export
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
