---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m

  dependsOn:
    - name: traefik
      namespace: networking

  values:
    image:
      repository: ghcr.io/onedr0p/prowlarr-develop
      tag: 1.9.3.4013

    env:
      TZ: "${TZ}"

    podAnnotations:
      backup.velero.io/backup-volumes: config

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      supplementalGroups:
        - 44
        - 109
        - 100

    service:
      main:
        ports:
          http:
            port: 9696

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdi:folder-search-outline"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-sso@kubernetescrd"
        hosts:
          - host: "prowlarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "prowlarr.${SECRET_DOMAIN}"

    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config-v1

    resources:
      requests:
        cpu: "0.04"
        memory: "256M"
      limits:
        memory: "512M"
