---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  dependsOn:
    - name: traefik
      namespace: networking

  values:

    image:
      repository: ghcr.io/onedr0p/qbittorrent
      tag: 4.5.5

    env:
      TZ: ${TZ}
      QBITTORRENT__PORT: &port 8080
      QBITTORRENT__BT_PORT: &bittorrentPort 6881

    service:
      main:
        ports:
          http:
            port: *port
      bittorrent:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${METALLB_QBIT_ADDR}
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${METALLB_QBIT_ADDR}
        externalTrafficPolicy: Local
        ports:
          bittorrent:
            enabled: true
            protocol: TCP
            port: *bittorrentPort
            targetPort: *bittorrentPort

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdi:cloud-download"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-sso@kubernetescrd"

        hosts:
          - host: "qbittorrent.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "qbittorrent.${SECRET_DOMAIN}"
      api:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
        hosts:
          - host: "qbittorrent.${SECRET_DOMAIN}"
            paths:
              - path: /api
                pathType: Prefix
        tls:
          - hosts:
              - "qbittorrent.${SECRET_DOMAIN}"

    persistence:
      cache:
        enabled: true
        type: emptyDir
        mountPath: /config/qBittorrent/cache
      config:
        enabled: true
        existingClaim: qbittorrent-config-v1
      media:
        enabled: true
        readOnly: false
        mountPath: /nfs-media
        existingClaim: nfs-media-pvc

    resources:
      requests:
        memory: 250Mi
        cpu: 10m
      limits:
        memory: 2000Mi
