---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 13.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.4.0
    env:
      TZ: "America/Toronto"
      WAIT_FOR_VPN: "true"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "cloud-download"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "qbittorrent.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "qbittorrent.${SECRET_DOMAIN}"
      api:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
        hosts:
          - host: "qbittorrent.${SECRET_DOMAIN}"
            paths:
              - path: /api
                pathType: Prefix
        tls:
          - hosts:
              - "qbittorrent.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config-v1
      media:
        enabled: true
        readOnly: false
        mountPath: /nfs-media
        existingClaim: nfs-media-pvc
      # This volume is used to facilitate status reporting between QBT and the VPN client.
      shared:
        enabled: true
        type: emptyDir
        mountPath: /shared

    # VPN config section
    addons:
      vpn:
        enabled: true
        type: wireguard

        # Note that the security context below is default.  I am being explicit in case I tinker with
        # the parent context.
        securityContext:
          runAsUser: 568
          runAsGroup: 568
        wireguard:
          image:
            repository: ghcr.io/k8s-at-home/wireguard
            tag: v1.0.20210914
        configFileSecret: qbittorrent-vpn-secret
        env:
          TZ: "America/Toronto"
          IPTABLES_BACKEND: nft
          KILLSWITCH: true
        scripts:
          up: |-
            #!/bin/bash
            echo "connected" > /shared/vpnstatus
          down: |-
            #!/bin/bash
            echo "disconnected" > /shared/vpnstatus

      codeserver:
        enabled: true

        image:
          repository: ghcr.io/k8s-at-home/code-server
          tag: v4.0.2

        workingDir: "/config"

        ingress:
          enabled: true
          ingressClassName: "traefik"
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
            hajimari.io/enable: "true"
            hajimari.io/icon: "microsoft-visual-studio-code"
          hosts:
            - host: "qbt-vscode.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - "qbt-vscode.${SECRET_DOMAIN}"

        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"

        volumeMounts:
          - name: config
            mountPath: /config
            existingClaim: qbittorrent-config-v1

        resources:
          requests:
            cpu: 35m
            memory: 128Mi
          limits:
            memory: 512Mi


    podSecurityContext:
      supplementalGroups:
        - 5600
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 2000Mi
