---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-pvc.yaml
  - helmrelease.yaml
  - secret.sops.yaml
  - dashboard
    #  - network-policy.yaml
configMapGenerator:
  - name: qbittorrent-dnsdist
    files:
      - ./config/dnsdist.conf
generatorOptions:
  disableNameSuffixHash: true
