apiVersion: v1
kind: Secret
metadata:
    name: wireguard
    namespace: media
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:ki8JmgYrO7CCO1SIvec6kYx54snODpKWeBFo5MVlh69+m58Wz0JNnisgFvY=,iv:uKpJvbqm4GH/hFGmU2QJtVGGoJ6q22jFQUG3G5ZUcpk=,tag:k/XsUWC+cQPR+ym/MA8qvg==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:R3J/EJFj1lDQ,iv:1KVPwrkUWOE6x0ecGzgFbdmLy5pHUD/qRy4u9Ai9llQ=,tag:Q0c7fWyjBaH19CWzI7urdg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:GZ25rfmVs8F1+Y5C,iv:ZtfDA14nXMkeO/P48Qp8jVkJTe2+XfyZxO+RkZxgB+4=,tag:EZZuwGDwfepJrG36wT5Vrw==,type:str]
    SERVER_REGIONS: ENC[AES256_GCM,data:4ouF58N4QCWX,iv:A/f73GuzTH4f0tBvfTLylkfdbix07/bYJYa0TKLJu2E=,tag:Lhxu5HLflxpeBmf12bF5Yw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146q3v4ent838axktd2jq49v48pctuhhmv49843wnmlygv8r2uyysjs8mfd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQk9jcnpsUjBCQStzM2pZ
            aXM2NnRkMHMyN3F3Sm5yV1BNVGVQQkpFYldNCkE1UVIxQjc3Z1JTSXZkSXhsOERP
            UDc4WTFHMHE3T2V0d0E5a0tCaG1HTlEKLS0tIGlBekJxN2dMdlNpQzFUd01Sa2pi
            SVFEVjdTRXY5dmlZTU1uMmZxb3lpQjAKDgZkM6hzMA90i7TEnXPjM1T09zP0XxXZ
            L3ei6/iXmnRJPVyoHBNXWuDuTKLmvRKT8TbXuyRZrEKPNk+gGk8CEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-22T20:31:00Z"
    mac: ENC[AES256_GCM,data:0uQNujW3Nt9/Ziz2zgx+pLsY/y7aMX6PUFBknlgo7dS6a1K6kgF66N5Xvyu0Tj97tGbCAHuhIMDYxrc2RwSyMQFG8fdgjCuzc0Ee+gRqus9AHP/S+MxsXL8Wtf8JW1/n7JqhOwNFfudpKZ763dLsO2NFW1eDHrDSgQ26UkqjXL0=,iv:a4CTaH+x9ogw/M+DhLryGwn8rbIWAJi1PSd1xbj3sL0=,tag:lOsMcg4G2X/8qCqjfHKnyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
