apiVersion: v1
kind: Secret
metadata:
    name: wireguard
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:SGGlIaJ2zD6Z8cqlube9UMx627xFU6sP0+SLJCc7FgdrVQNUtizKjbuLu60=,iv:mu/9H4DNA4xxd/zUtowe5fPNM8q9xdLUfTaNO1OZ7/Q=,tag:GTVGsSzb35lW+ew3+rOqfw==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:R3J/EJFj1lDQ,iv:1KVPwrkUWOE6x0ecGzgFbdmLy5pHUD/qRy4u9Ai9llQ=,tag:Q0c7fWyjBaH19CWzI7urdg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:GZ25rfmVs8F1+Y5C,iv:ZtfDA14nXMkeO/P48Qp8jVkJTe2+XfyZxO+RkZxgB+4=,tag:EZZuwGDwfepJrG36wT5Vrw==,type:str]
    SERVER_REGIONS: ENC[AES256_GCM,data:5hhW2aymWA8Ur45hANg=,iv:eJgnn5xjeAZWGbqNW7ShnMryXcjRmZ+96zDn/ka9nJs=,tag:qG1AJ/gaMGMl41K/Is48bg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146q3v4ent838axktd2jq49v48pctuhhmv49843wnmlygv8r2uyysjs8mfd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQk9jcnpsUjBCQStzM2pZ
            aXM2NnRkMHMyN3F3Sm5yV1BNVGVQQkpFYldNCkE1UVIxQjc3Z1JTSXZkSXhsOERP
            UDc4WTFHMHE3T2V0d0E5a0tCaG1HTlEKLS0tIGlBekJxN2dMdlNpQzFUd01Sa2pi
            SVFEVjdTRXY5dmlZTU1uMmZxb3lpQjAKDgZkM6hzMA90i7TEnXPjM1T09zP0XxXZ
            L3ei6/iXmnRJPVyoHBNXWuDuTKLmvRKT8TbXuyRZrEKPNk+gGk8CEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-12T14:40:20Z"
    mac: ENC[AES256_GCM,data:SaEDo4Ib1hYng19G2BFcVWCpc3Vkh0WWefStQ2YoeAY0emtYJiv1jMKEqsvqSkrQWeyHYKCTFzK9rnkcWB8D03vAW+HjiUw5YATHL0vqrWZrV6k3w+Me1Hbiu8MJoIG38+4fMUdjrfeMAx0Xr8z/0JIcn3sltL7J2MjV0Ppz08Q=,iv:KlvplfEZjlNN6tQ6tCkEU8mQHvWV4WQ98nHazQj8X8o=,tag:bqnkkyRvKLqXosEOTiSxKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
