apiVersion: v1
kind: Secret
metadata:
    name: wireguard
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:ki8JmgYrO7CCO1SIvec6kYx54snODpKWeBFo5MVlh69+m58Wz0JNnisgFvY=,iv:uKpJvbqm4GH/hFGmU2QJtVGGoJ6q22jFQUG3G5ZUcpk=,tag:k/XsUWC+cQPR+ym/MA8qvg==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:R3J/EJFj1lDQ,iv:1KVPwrkUWOE6x0ecGzgFbdmLy5pHUD/qRy4u9Ai9llQ=,tag:Q0c7fWyjBaH19CWzI7urdg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:GZ25rfmVs8F1+Y5C,iv:ZtfDA14nXMkeO/P48Qp8jVkJTe2+XfyZxO+RkZxgB+4=,tag:EZZuwGDwfepJrG36wT5Vrw==,type:str]
    SERVER_REGIONS: ENC[AES256_GCM,data:XVWQymFRS9JHGyze5+Hjrw==,iv:6c2YBzVQZejJdKyZq7pWJo6bXiXFiBUbnB0VYiqYWjs=,tag:874cdOe6X8CgOQ5Sj8SLRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146q3v4ent838axktd2jq49v48pctuhhmv49843wnmlygv8r2uyysjs8mfd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQk9jcnpsUjBCQStzM2pZ
            aXM2NnRkMHMyN3F3Sm5yV1BNVGVQQkpFYldNCkE1UVIxQjc3Z1JTSXZkSXhsOERP
            UDc4WTFHMHE3T2V0d0E5a0tCaG1HTlEKLS0tIGlBekJxN2dMdlNpQzFUd01Sa2pi
            SVFEVjdTRXY5dmlZTU1uMmZxb3lpQjAKDgZkM6hzMA90i7TEnXPjM1T09zP0XxXZ
            L3ei6/iXmnRJPVyoHBNXWuDuTKLmvRKT8TbXuyRZrEKPNk+gGk8CEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-05T14:54:56Z"
    mac: ENC[AES256_GCM,data:FXY0faRkspmXFd7d2ZFPCNE6r3igmwsyGdkmMEjOWMaznnC+WoEEkzVnAFQlk8q/9lV0ZvkMa7xRWeL4chZlK895mO6n6YTXKTczyxiSRrOiQRAaauBFT6x2fRlGvJr7zIfqohdRHmV87jvPyAkwKWBW0+UNdyWx+pBTh79JslE=,iv:GfBRQJI8hkseGijgEygrM4X77rn5r0V231yUOMk1pk0=,tag:8DgK5RRdbrrcnium2HFFng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
