---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-config-v1
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 1Gi
