---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tdarr
  namespace: media
spec:
  dependsOn:
    - name: traefik
      namespace: networking
  maxHistory: 3
  interval: 5m
  suspend: false
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: tdarr
      version: 4.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: haveagitgat/tdarr
      tag: 2.00.13
      pullPolicy: IfNotPresent
    env:
      TZ: ${TZ}
      serverIP: 0.0.0.0
      ffmpegPath: /usr/bin/ffmpeg
    node:
      enabled: true
      id: node
      image:
        repository: haveagitgat/tdarr_node
        tag: 2.00.13
        pullPolicy: IfNotPresent
    persistence:
      data:
        enabled: true
        mountPath: /app/server
        existingClaim: tdarr-config-v1
      shared:
        enabled: true
        type: emptyDir
        mountPath: /shared
      media:
        enabled: true
        readOnly: false
        mountPath: /Data
        existingClaim: nfs-media-pvc
    service:
      main:
        ports:
          http:
            port: 8265
          server:
            enabled: true
            protocol: TCP
            port: 8266
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: alpha-t-circle
        hosts:
          - host: "tdarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "tdarr.${SECRET_DOMAIN}"

    resources: {}
