---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi-poller
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: unifi-poller
      version: 10.3.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/k8s-at-home/unpoller
      tag: 2.1.3
    env:
      TZ: "${TZ}"
      UP_UNIFI_DEFAULT_URL: "${CONFIG_UNIFIPOLLER_UNIFI_URL}"
      UP_UNIFI_DEFAULT_VERIFY_SSL: false
      UP_UNIFI_DEFAULT_USER: "unifipoller"
      UP_UNIFI_DEFAULT_PASS: "${SECRET_UNIFIPOLLER_PASS}"
      UP_UNIFI_DEFAULT_SAVE_SITES: true
      UP_UNIFI_DEFAULT_SAVE_DPI: false
      UP_UNIFI_DEFAULT_SAVE_EVENTS: false
      UP_UNIFI_DEFAULT_SAVE_ALARMS: false
      UP_INFLUXDB_DISABLE: true
      UP_PROMETHEUS_DISABLE: false
      UP_PROMETHEUS_NAMESPACE: "unifipoller"
    metrics:
      enabled: true
      serviceMonitor:
        interval: 1m
        scrapeTimeout: 30s
      prometheusRule:
        enabled: true
