---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app snmp-exporter-idrac
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: prometheus-snmp-exporter
      version: 9.12.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 5m
  values:
    fullnameOverride: *app
    nameOverride: *app
    extraArgs:
      - "--config.file=/config/snmp.yaml"
    extraConfigmapMounts:
      - name: *app
        mountPath: /config/snmp.yaml
        subPath: snmp.yaml
        configMap: snmp-exporter-idrac
        readOnly: true
        defaultMode: 420
    serviceMonitor:
      enabled: true
      namespace: monitoring
      module:
        - dell_idrac
      params:
        - name: idrac0
          target: 10.0.0.88
        - name: idrac1
          target: 10.0.0.89
      path: /snmp
      scrapeTimeout: 30s
      relabelings:
        - sourceLabels: [__param_target]
          targetLabel: instance
