apiVersion: v1
kind: Secret
metadata:
    name: prometheus-hass
    namespace: home
stringData:
    token: ENC[AES256_GCM,data:AmvihPqYWzd7O4eMKu5NqxoYFkMYkpqVTlwQ5EnzkJAG6Ti78Ll5iDjK5rJf/NQttiSTzySGJzLSQTuGaKrLpt8emv6BMoIsKzJP/4r0LANGcfesiUJ5tRzvdjym/h1HEi2QwIg1zrK2VnE/m40edvMvVgLhW0kjCoOsBTRhhG5307H9xHJ978RWeQ12Oyg448eSVkGBqEVlzr6c9YibU8WnoMPwuLmPODGUPwgX46iPcMzbjpy4,iv:DbtJDwZ7QNFqCXr3wH/aBXsT6idUktcgAFYht93LQQs=,tag:kk3FufpUKmsquCBGTcxoIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146q3v4ent838axktd2jq49v48pctuhhmv49843wnmlygv8r2uyysjs8mfd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOXFSTzY5WlBjVzgwOVEy
            aEhyOFJnSzVmQUxhVGlWRlRPeHFXSHlkZVMwClNTRUh4dVVDQmJHT25JaGR0Lzdv
            UmZKV09RRmx4T3hNV2lyYlRKeVgzcTgKLS0tIDZ1aGdrZkhwb1dsVVRJVnZMNWdH
            dS9UYU1LQURwZ0RvRHhNSTI3V2F0Mk0KKEpTHPjXtA3wUAcPbv7U9ZsvECDCdfTz
            jMsY+ISvEPswGt9I+kHgRYLMzp271zXqtsJiY26ZpRbFOLT5UgR4TQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-26T18:04:09Z"
    mac: ENC[AES256_GCM,data:mrQrATHNdxWY6gpSYzl5Z4SwFXybE9VkSJ0cXxdX5WHUwAYwYcJzmKLk3PD1ifXd9KPCa6fzXXT5cP+oh+RWi4xlWRf5LZ8C1sAh/ft9PVljLovDA7QO1FYyngNrhIPd05MkU1QElKGseSzTs28xuRqvKk38DM0NbqoxO3Rcwbw=,iv:kcosso46YTgLiEXzZfRQkskK1MzKy1ux8zTAj1OcDqM=,tag:rAiXz1Bbuhy+08xdqosaMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
