---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: vpn-gateway
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: pod-gateway
      version: 5.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    image:
      repository: ghcr.io/k8s-at-home/pod-gateway
      tag: v1.4.0

    DNS: 172.16.1.1

    env:
      TZ: "${TZ}"

    routed_namespaces:
      - media

    publicPorts:
      - hostname: "qbittorrent" # hostname assigned to the pod
        IP: 10 # must be an integer between 2 and VXLAN_GATEWAY_FIRST_DYNAMIC_IP (20 by default)
        ports:
          - type: udp
            port: ${VPN_FORWARDED_PORT_1}
          - type: tcp
            port: ${VPN_FORWARDED_PORT_1}

    settings:
      NOT_ROUTED_TO_GATEWAY_CIDRS: "172.16.0.0/12 ${NETWORK_K8S_CLUSTER_CIDR} ${NETWORK_K8S_SERVICE_CIDR} ${CONFIG_LOCAL_NETWORK}"
      VPN_LOCAL_CIDRS: "172.16.0.0/12 ${NETWORK_K8S_CLUSTER_CIDR} ${NETWORK_K8S_SERVICE_CIDR} ${CONFIG_LOCAL_NETWORK}"
      DNS_LOCAL_CIDRS: "local ${SECRET_DOMAIN}"
      VPN_INTERFACE: wg0
      VXLAN_ID: 43
      VXLAN_IP_NETWORK: 172.16.1
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_TRAFFIC_PORT: "${SECRET_VPN_GATEWAY_PORT}"

    webhook:
      image:
        repository: ghcr.io/k8s-at-home/gateway-admision-controller
        tag: v3.4.0

      gatewayDefault: false
      gatewayLabel: setGateway
      gatewayAnnotation: setGateway
      namespaceSelector:
        label: "routed-gateway"

    livenessProbe:
      exec:
        command:
          - sh
          - -c
          - if [ $(curl -s https://am.i.mullvad.net/country) = '${VPN_COUNTRY}' ]; then exit 0; else exit $?; fi
      initialDelaySeconds: 30
      periodSeconds: 60
      failureThreshold: 1

    addons:
      netshoot:
        enabled: true

      vpn:
        enabled: true
        type: wireguard
        wireguard:
          image:
            repository: ghcr.io/k8s-at-home/wireguard
            tag: v1.0.20210914
            pullPolicy: IfNotPresent

        securityContext:
          runAsUser: 568
          runAsGroup: 568
          capabilities:
            drop:
              - "SYS_MODULE"

        env:
          TZ: "${TZ}"
          IPTABLES_BACKEND: nft
          KILLSWITCH: false
          # KILLSWITCH: true
          # KILLSWITCH_EXCLUDEDNETWORKS_IPV4: "${NETWORK_K8S_CLUSTER_CIDR};${NETWORK_K8S_SERVICE_CIDR};${CONFIG_LOCAL_NETWORK}"
        configFileSecret: vpn-gateway-vpnsecret

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 512Mi
        scripts:
          up: |-
            #!/bin/bash
            echo "connected" > /config/vpnstatus

          down: |-
            #!/bin/bash
            echo "disconnected" > /config/vpnstatus

        networkPolicy:
          enabled: true

          egress:
            - to:
                - ipBlock:
                    cidr: 0.0.0.0/0
              ports:
                - port: ${VPN_GATEWAY_VPN_PORT}
                  protocol: UDP
            - to:
                - namespaceSelector: {}
