---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: vpn-gateway
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: pod-gateway
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m

  # See https://github.com/k8s-at-home/charts/blob/master/charts/pod-gateway/values.yaml
  values:
    image:
      repository: ghcr.io/k8s-at-home/pod-gateway
      tag: v1.4.0
    routed_namespaces:
      - media
    settings:
      NOT_ROUTED_TO_GATEWAY_CIDRS: "10.42.0.0/16 10.43.0.0/16 172.22.0.0/12 10.0.0.0/24 ${CONFIG_LOCAL_NETWORK}"
      VXLAN_IP_NETWORK: "${CONFIG_VPNGATEWAY_NETWORK}"
      VPN_INTERFACE: tun0 # tun0 for openvpn, wg0 for wireguard
      VXLAN_ID: 43
      # VPN_BLOCK_OTHER_TRAFFIC: true
      # VPN_TRAFFIC_PORT: "${SECRET_VPN_GATEWAY_PORT}"
    webhook:
      image:
        repository: ghcr.io/k8s-at-home/gateway-admision-controller
        tag: v3.4.0
      gatewayDefault: false
      gatewayLabel: setGateway
      gatewayAnnotation: setGateway
      namespaceSelector:
        label: "vpn-routed-gateway"
