---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-postgres-pv
  namespace: default
spec:
  storageClassName: postgres
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${NFS_SERVER}"
    path: "/volume5/AIML/postgres"
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
