---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: traefik-crd-source
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/traefik/traefik-helm-chart.git
  ref:
    # renovate: registryUrl=https://helm.traefik.io/traefik chart=traefik
    tag: v26.0.0
  ignore: |
    # exclude all
    /*
    # path to crds
    !/traefik/crds/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-crds
  namespace: flux-system
spec:
  interval: 15m
  prune: false
  sourceRef:
    kind: GitRepository
    name: traefik-crd-source
  healthChecks:
    # These are legacy CRDs that I've removed from config.  Disabling here so I can't reintroduce dependency.
    # - apiVersion: apiextensions.k8s.io/v1
    #   kind: CustomResourceDefinition
    #   name: ingressroutes.traefik.containo.us
    # - apiVersion: apiextensions.k8s.io/v1
    #   kind: CustomResourceDefinition
    #   name: ingressroutetcps.traefik.containo.us
    # - apiVersion: apiextensions.k8s.io/v1
    #   kind: CustomResourceDefinition
    #   name: ingressrouteudps.traefik.containo.us
    # - apiVersion: apiextensions.k8s.io/v1
    #   kind: CustomResourceDefinition
    #   name: middlewares.traefik.containo.us
    # - apiVersion: apiextensions.k8s.io/v1
    #   kind: CustomResourceDefinition
    #   name: middlewaretcps.traefik.containo.us
    # - apiVersion: apiextensions.k8s.io/v1
    #   kind: CustomResourceDefinition
    #   name: serverstransports.traefik.containo.us
    # - apiVersion: apiextensions.k8s.io/v1
    #   kind: CustomResourceDefinition
    #   name: tlsoptions.traefik.containo.us
    # - apiVersion: apiextensions.k8s.io/v1
    #   kind: CustomResourceDefinition
    #   name: tlsstores.traefik.containo.us
    # - apiVersion: apiextensions.k8s.io/v1
    #   kind: CustomResourceDefinition
    #   name: traefikservices.traefik.containo.us
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: ingressroutes.traefik.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: ingressroutetcps.traefik.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: ingressrouteudps.traefik.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: middlewares.traefik.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: middlewaretcps.traefik.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: serverstransports.traefik.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: serverstransporttcps.traefik.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: tlsoptions.traefik.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: tlsstores.traefik.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: traefikservices.traefik.io
