---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: external-auth
  namespace: networking
spec:
  chain:
    middlewares:
      - name: cloudflare-ips
      - name: networking-authentik@kubernetescrd
      - name: chain-no-auth@kubernetescrd
