---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: authentik
  namespace: networking
spec:
  forwardAuth:
    address: https://id.${SECRET_DOMAIN}/akprox/auth/traefik
    trustForwardHeader: true
    authResponseHeadersRegex: ^.*$
