---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare.yaml
  - redirect-path.yaml
  - rfc1918.yaml
  - secure-headers.yaml
  - rate-limit.yaml
  - chain-no-auth.yaml
  - traefik-sso.yaml
