---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: sso
  namespace: networking
spec:
  chain:
    middlewares:
      - name: traefik-forward-auth
      - name: error-pages
      # and others probably?
