---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: sso
  namespace: networking
spec:
  chain:
    middlewares:
      - name: traefik-forward-auth
      # and others probably?
