---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: websocket-headers
  namespace: networking
spec:
  headers:
    customRequestHeaders:
      Upgrade: WebSocket
      Connection: Upgrade
      X-Forwarded-Proto: https
