---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: kured
      version: 4.5.0
      sourceRef:
        kind: HelmRepository
        name: kubereboot
        namespace: flux-system
  values:
    updateStrategy: RollingUpdate
    configuration:
      timeZone: ${TZ}
      startTime: "1am"
      endTime: "5am"
      notifyUrl: ${SECRET_KURED_DISCORD_WEBHOOK}
      rebootSentinelCommand: |-
        sh -c "! needs-restarting --reboothint"
    metrics:
      create: true
