---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://weaveworks.github.io/kured
      chart: kured
      version: 2.14.0
      sourceRef:
        kind: HelmRepository
        name: weaveworks-kured-charts
        namespace: flux-system
  values:
    updateStrategy: RollingUpdate
    configuration:
      timeZone: ${TZ}
#      startTime: "3:00"
#      endTime: "5:00"
      notifyUrl: ${SECRET_KURED_DISCORD_WEBHOOK}
    metrics:
      create: true
