---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m

  dependsOn:
    - name: traefik
      namespace: networking

  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      pullPolicy: IfNotPresent
      tag: 2023.7.3

    env:
      TZ: "${TZ}"

    envFrom:
      - secretRef:
          name: home-assistant-secrets

    service:
      main:
        type: LoadBalancer
        externalIPs:
          - ${METALLB_HOMEASSISTANT_ADDR}
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8123

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: true

    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-v1

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "home-assistant"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "homeassistant.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "homeassistant.${SECRET_DOMAIN}"
            secretName: "homeassistant-tls"

    resources:
      requests:
        cpu: 75m
        memory: 512Mi
      limits:
        memory: 2048Mi

          #    metrics:
          #      enabled: true
          #      serviceMonitor:
          #        interval: 1m
          #        scrapeTimeout: 30s
          #      prometheusRule:
          #        enabled: true

    addons:
      codeserver:
        enabled: true

        image:
          repository: codercom/code-server
          tag: 4.16.1

        workingDir: "/config"

        ingress:
          enabled: true
          ingressClassName: "traefik"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-production"
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
            hajimari.io/enable: "true"
            hajimari.io/icon: "microsoft-visual-studio-code"
            traefik.ingress.kubernetes.io/router.middlewares: "networking-sso@kubernetescrd"
          hosts:
            - host: "ha-vscode.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - "ha-vscode.${SECRET_DOMAIN}"
              secretName: "ha-vscode-tls"

        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"

        volumeMounts:
          - name: config
            mountPath: /config

        resources:
          requests:
            cpu: 35m
            memory: 128Mi
          limits:
            memory: 512Mi
