---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m

  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  dependsOn:
    - name: traefik
      namespace: networking

  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups:
          - 65539

    controllers:
      main:
        annotations:
          backup.velero.io/backup-volumes: config
        containers:
          main:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              pullPolicy: IfNotPresent
              tag: 2024.2.5
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: true
            resources:
              requests:
                cpu: 75m
                memory: 512Mi
              limits:
                memory: 2048Mi

            env:
              TZ: "${TZ}"

            envFrom:
              - secretRef:
                  name: home-assistant-secrets

          codeserver:
            image:
              repository: codercom/code-server
              pullPolicy: IfNotPresent
              tag: 4.22.1
            env:
              TZ: ${TZ}
            args:
              - "/config"
              - --auth
              - "none"
              - --user-data-dir
              - "/config/.vscode"
              - --extensions-dir
              - "/config/.vscode"

          whisper: # Speech to Text
            image:
              repository: rhasspy/wyoming-whisper
              pullPolicy: IfNotPresent
              tag: 1.0.0
            env:
              TZ: ${TZ}
            args:
              - --model
              - "small"
              - --language
              - "en"
              - --beam-size
              - "1"
            resources:
              requests:
                cpu: 10m
                memory: 396Mi
              limits:
                cpu: 500m
                memory: 512Gi

          piper: # Text to Speech
            image:
              repository: rhasspy/wyoming-piper
              pullPolicy: IfNotPresent
              tag: 1.5.0
            env:
              TZ: ${TZ}
            args:
              - --voice
              - "en-us-libritts-high"
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                cpu: 500m
                memory: 256Gi

          openwakeword: # Text to Speech
            image:
              repository: rhasspy/wyoming-openwakeword
              pullPolicy: IfNotPresent
              tag: 1.8.1
            env:
              TZ: ${TZ}
            args:
              - --preload-model
              - ok_nabu
              - --custom-model-dir
              - /custom
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                cpu: 500m
                memory: 256Gi

    service:
      main:
        ports:
          http:
            port: 8123
      codeserver:
        type: ClusterIP
        controller: main
        ports:
          http:
            enabled: true
            port: 8080
      whisper:
        type: ClusterIP
        controller: main
        ports:
          whisper:
            port: 10300
      piper:
        type: ClusterIP
        controller: main
        ports:
          piper:
            port: 10200
      openwakeword:
        type: ClusterIP
        controller: main
        ports:
          openwakeword:
            port: 10400

    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-v1
      whisper-data:
        enabled: true
        type: emptyDir
        advancedMounts:
          main:
            piper:
              - path: /data
                readOnly: false
      piper-data:
        enabled: true
        type: emptyDir
        advancedMounts:
          main:
            whisper:
              - path: /data
                readOnly: false
      openwakeword:
        enabled: true
        existingClaim: openwakeword-data-v1
        advancedMounts:
          main:
            openwakeword:
              - path: /data
                subPath: data
              - path: /custom
                subPath: custom
    ingress:
      main:
        enabled: true
        className: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "home-assistant"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host "homeassistant.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: "homeassistant-tls"
      codeserver:
        enabled: true
        className: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: simple-icons:vs-code
          hajimari.io/info: Programs esphome devices
          hajimari.io/group: automation
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-sso@kubernetescrd"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &codehost ha-vscode.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: codeserver
                  port: http
        tls:
          - hosts:
              - *codehost
            secretName: "tls.ha-vscode"
