---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m

  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  dependsOn:
    - name: traefik
      namespace: networking

  values:
    controllers:
      main:
        annotations:
          backup.velero.io/backup-volumes: config
        containers:
          main:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              pullPolicy: IfNotPresent
              tag: 2023.12.4
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: true
            resources:
              requests:
                cpu: 75m
                memory: 512Mi
              limits:
                memory: 2048Mi

            env:
              TZ: "${TZ}"

            envFrom:
              - secretRef:
                  name: home-assistant-secrets

          codeserver:
            image:
              repository: codercom/code-server
              pullPolicy: IfNotPresent
              tag: 4.20.0
            env:
              TZ: ${TZ}
            args:
              - "/config"
              - --auth
              - "none"
              - --user-data-dir
              - "/config/.vscode"
              - --extensions-dir
              - "/config/.vscode"
            volumeMounts:
              - name: config
                mountPath: /config

    service:
      main:
        ports:
          http:
            port: 8123
      codeserver:
        type: ClusterIP
        controller: main
        ports:
          http:
            enabled: true
            port: 8080

    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-v1

    ingress:
      main:
        enabled: true
        className: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "home-assistant"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host "homeassistant.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: "homeassistant-tls"
      codeserver:
        enabled: true
        className: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: simple-icons:vs-code
          hajimari.io/info: Programs esphome devices
          hajimari.io/group: automation
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &codehost ha-vscode.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: codeserver
                  port: http
        tls:
          - hosts:
              - *codehost
            secretName: "tls.ha-vscode"
