---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #Pre-flux kustomizations (todo)
  - media-pv.yaml
  - jellyfin
  - plex
  - radarr
  - sonarr
  - qbittorrent
  - prowlarr
  # - bazarr
  - overseerr
  - threadfin
  - immich
  # flux kustomizations
  - ./youtubedl-material/ks.yaml
  - ./bazarr/ks.yaml
