---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - media-pv.yaml
  - jellyfin
  - plex
  - radarr
  - sonarr
  - qbittorrent
  - prowlarr
  - bazarr
  - overseerr
  - threadfin
  - immich
  - youtubedl-material
