---
# https://huggingface.co/waifu-diffusion/wd-1-5-beta2
# https://huggingface.co/waifu-diffusion/wd-1-5-beta
# https://huggingface.co/hakurei/waifu-diffusion-v1-4
apiVersion: batch/v1
kind: Job
metadata:
  name: install-model-wd15b2
spec:
  template:
    spec:
      containers:
        - name: downloader
          image: busybox:1@sha256:768e5c6f5cb6db0794eec98dc7a967f40631746c32232b78a3105fb946f3ab83
          volumeMounts:
            - name: shared-embeddings
              mountPath: /shared-embeddings
            - name: shared-models
              mountPath: /shared-models
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              echo "started" \
              && DIR=/shared-embeddings \
              && mkdir -v -p "$DIR" \
              && DST="$DIR"/wdgoodprompt.bin \
              && if [ ! -f "$DST" ] ; then wget https://huggingface.co/waifu-diffusion/wd-1-5-beta/resolve/main/embeddings/wdgoodprompt.bin -O "$DST" ; fi \
              && DST="$DIR"/wdbadprompt.pt \
              && if [ ! -f "$DST" ] ; then wget https://huggingface.co/waifu-diffusion/wd-1-5-beta/resolve/main/embeddings/wdbadprompt.pt -O "$DST" ; fi \
              && DIR=/shared-models/Stable-diffusion \
              && mkdir -v -p "$DIR" \
              && DST="$DIR"/wd-1-5-beta2-fp32.yaml \
              && if [ ! -f "$DST" ] ; then wget https://huggingface.co/waifu-diffusion/wd-1-5-beta2/resolve/main/checkpoints/wd-1-5-beta2-fp32.yaml -O "$DST" ; fi \
              && DST="$DIR"/wd-1-5-beta2-fp32.safetensors \
              && if [ ! -f "$DST" ] ; then wget https://huggingface.co/waifu-diffusion/wd-1-5-beta2/resolve/main/checkpoints/wd-1-5-beta2-fp32.safetensors -O "$DST" ; fi \
              && DST="$DIR"/wd-1-5-beta2-fp32.vae.pt \
              && if [ ! -f "$DST" ] ; then wget https://huggingface.co/hakurei/waifu-diffusion-v1-4/resolve/main/vae/kl-f8-anime2.ckpt -O "$DST" ; fi \
              && echo "completed"
      volumes:
        - name: shared-embeddings
          persistentVolumeClaim:
            claimName: nfs-aiml-pvc-embeddings
        - name: shared-models
          persistentVolumeClaim:
            claimName: nfs-aiml-pvc-models
      restartPolicy: Never
  backoffLimit: 3
