---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - prometheus-rule.yaml
  - letsencrypt-production.yaml
  - letsencrypt-staging.yaml
  - secret-cloudflareapi.sops.yaml
  - secret-pkcs12.sops.yaml
  - certificate.yaml
