---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lemmy
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m

  dependsOn:
    - name: traefik
      namespace: networking

  values:
    image:
      repository: dessalines/lemmy
      pullPolicy: IfNotPresent
      tag: 0.18.0
    env:
      TZ: "${TZ}"
      RUST_LOG: "warn,lemmy_server=debug,lemmy_api=debug,lemmy_api_common=debug,lemmy_api_crud=debug,lemmy_apub=debug,lemmy_db_schema=debug,lemmy_db_views=debug,lemmy_db_views_actor=debug,lemmy_db_views_moderator=debug,lemmy_routes=debug,lemmy_utils=debug,lemmy_websocket=debug"
      RUST_BACKTRACE: "full"

    podSecurityContext:
      runAsUser: 991
      runAsGroup: 991
      fsGroup: 991

    secrets:
      config:
        enabled: true
        stringData:
          config.hjson: |
            {
              setup: {
                admin_username: "${SECRET_LEMMY_ADMINUSER}"
                admin_password: "${SECRET_LEMMY_ADMINPASS}"
                site_name: "Hampstead Lemmy"
                # enable_downvotes: true  ?? IU guess these fields aren't valid in docker?
                # open_registration: false
                # enable_nsfw: true
              }

              federation: {
                enabled: true
              }

              hostname: "lemmy.${SECRET_DOMAIN}"
              bind: "0.0.0.0"
              port: 8536
              tls_enabled: true
              jwt_secret: "${SECRET_LEMMY_ADMINPASS}"

              pictrs: {
                url: "http://pictrs:8080/"
              }

              # email: {
              #   smtp_server: "localhost:25"
              #   smtp_login: "string"
              #   smtp_password: "string"
              #   smtp_from_address: "noreply@example.com"
              #   tls_type: "none"
              # }

              database: {
                  user: "postgres"
                  password: "${SECRET_PG_ADMINPASS}"
                  host: "cluster-lemmy-rw"
                  port: 5432
                  database: "lemmy"
                  pool_size: 3
                }
            }
    # TODO: This requires a bit of first-run and subsequent run setup.  Learn how to define that in a manifest and fix this.  For now commit once to init and commit again for launch.
    persistence:
      config:
        enabled: true
        name: lemmy-config
        type: secret
        mountPath: /config/config.hjson
        subPath: config.hjson
        readOnly: true

    service:
      main:
        ports:
          http:
            port: 8536
