---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: youtubedl-material
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m

  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph

  values:
    controllers:
      main:
        pod:
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 65539
        annotations:
          backup.velero.io/backup-volumes: data
          configmap.reloader.stakater.com/reload: youtubedl-material-dnsdist
          secret.reloader.stakater.com/reload: qbittorrent-secret
        containers:
          main:
            image:
              # renovate: depName=docker.com/tzahi12345/youtubedl-material datasource=docker
              repository: tzahi12345/youtubedl-material
              # tag: "4.2"
              tag: latest # I ALSO like to live dangerously
              pullPolicy: IfNotPresent
            resources:
              requests:
                memory: "128M"
              limits:
                memory: "512M"
            env:
              TZ: "${TZ}"

          # Configure the gluetun sidecar
          gluetun:
            dependsOn: main
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.37.0
            # -- environment variables.
            # See [image docs](https://github.com/qdm12/gluetun-wiki) for more details on how to configure your VPN and how to set up port-forwarding.
            env:
              VPN_TYPE: wireguard
              VPN_INTERFACE: wg0
              FIREWALL_INPUT_PORTS: 17442
              FIREWALL_OUTBOUND_SUBNETS: "${NETWORK_K8S_SERVICE_CIDR},${NETWORK_K8S_CLUSTER_CIDR}"
              SHADOWSOCKS: "on"
              HTTPPROXY: "on"
              HTTPPROXY_LOG: "on"
              DOT: "off"
              DNS_ADDRESS: "127.0.0.16"  #Note this is a cross dependency to qbittorrent.  Meh.

            envFrom:
              - secretRef:
                  name: wireguard

            # Configure the container-specific securityContext
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
          dnsdist:
            image:
              repository: docker.io/powerdns/dnsdist-18
              tag: 1.8.3
            # Configure the container-specific securityContext
            securityContext:
              runAsUser: 0
              runAsGroup: 0

    service:
      main:
        ports:
          http:
            port: 17442

    persistence:
      data:
        enabled: true
        existingClaim: youtubedl-material-config-v1
        globalMounts:
          - path: /app/appdata
      audio:
        enabled: true
        existingClaim: nfs-youtubedl-audio-pvc
        readOnly: false
        globalMounts:
          - path: /app/audio
      subscriptions:
        enabled: true
        existingClaim: nfs-youtubedl-subscriptions-pvc
        readOnly: false
        globalMounts:
          - path: /app/subscriptions
      users:
        enabled: true
        existingClaim: nfs-youtubedl-users-pvc
        readOnly: false
        globalMounts:
          - path: /app/users
      video:
        enabled: true
        existingClaim: nfs-youtubedl-video-pvc
        readOnly: false
        globalMounts:
          - path: /app/video
      gluetun-data:
        type: emptyDir
        advancedMounts:
          main:
            gluetun:
              - path: /tmp/gluetun
      dnsdist-config:
        type: configMap
        name: qbittorrent-dnsdist
        advancedMounts:
          main:
            dnsdist:
              - path: /etc/dnsdist/dnsdist.conf
                subPath: dnsdist.conf
                readOnly: true

    ingress:
      main:
        enabled: true
        className: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "interrobang"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-sso@kubernetescrd"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host "youtube-dl.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: "youtube-dl-tls"
