---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-forward-auth
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 15
  install:
    timeout: 5m
    replace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
  uninstall:
    keepHistory: false
  rollback:
    recreate: true
    force: true
    cleanupOnFail: true
  dependsOn:
    - name: traefik
      namespace: networking


  values:
    controllers:
      traefik-forward-auth:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: thomseddon/traefik-forward-auth
              tag: v2.2.0@sha256:882e6c07e137ea23dac85afee30676d3bf676418d471bfa4df7c16da1567d45e
            env:
              TZ: ${TZ}
              AUTH_HOST: &host id.${SECRET_DOMAIN}
              DOMAIN: ${SECRET_DOMAIN}
              COOKIE_DOMAIN: ${SECRET_DOMAIN}
              INSECURE_COOKIE: "false"
              URL_PATH: /_oauth
              LOG_LEVEL: info
              # 1 week
              LIFETIME: "604800"
            envFrom:
              - secretRef:
                  name: &secret traefik-forward-auth-secrets
            resources:
              requests:
                cpu: 5m
                memory: 10Mi
              limits:
                memory: 50Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true

    service:
      app:
        controller: traefik-forward-auth
        ports:
          http:
            port: 4181

    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: networking-sso@kubernetescrd
        hosts:
          - host: *host
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: "{{ .Release.Name }}-tls"
