---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: velero
      version: 6.0.0
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
      interval: 5m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    configuration:
      extraEnvVars:
        TZ: "${TZ}"
      backupStorageLocation:
        - name: aws
          provider: aws
          bucket: velero
          default: true
          config:
            region: us-east-1
            s3ForcePathStyle: true
            s3Url: http://nas02.${SECRET_DOMAIN}:9000

      volumeSnapshotLocation:
        - name: aws
          provider: aws
          config:
            region: us-east-1

      resticTimeout: 6h

    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.9.2@sha256:c7f801bda8c89c1277377b8d07394da71de949246edf7b57988772c569d6f50d
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins

    credentials:
      existingSecret: velero-minio-credentials

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    backupsEnabled: true
    snapshotsEnabled: true
    upgradeCRDs: false  # This is handled in flux CRD yaml.

    deployNodeAgent: true
    nodeAgent:
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
      resources:
        requests:
          memory: 200Mi
          cpu: 15m
        limits:
          memory: 3000Mi
          cpu: 1000m

    schedules:
      daily-backup:
        schedule: "0 6 * * *"
        template:
          storageLocation: aws
          ttl: "336h"
