---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-immich
  namespace: media
data:
  DB_PORT: "5432"
  DISABLE_REVERSE_GEOCODING: "true"
  ENABLE_MAPBOX: "false"
  LOG_LEVEL: verbose
  NODE_ENV: "production"
  REDIS_PORT: "6379"
  REDIS_DBINDEX: "0"
  IMMICH_SERVER_URL: http://immich.media.svc.cluster.local:3001
  IMMICH_MACHINE_LEARNING_URL: http://immich-ml.media.svc.cluster.local:3003
