---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      automountServiceAccountToken: false

    controllers:
      main:
        type: deployment
        replicas: 2
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.1
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: immich-secret

        containers:
          main:
            order: 2
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.93.3
            args: ["start-server.sh"]
            envFrom:
              - secretRef:
                  name: &secret "secret-immich"
              - configMapRef:
                  name: &cm "configmap-immich"
            resources:
              requests:
                cpu: 100m
                memory: 512M
              limits:
                memory: 1Gi
      redis:
        type: deployment
        containers:
          main:
            order: 1
            image:
              repository: public.ecr.aws/docker/library/redis
              tag: 7.2.4
            env:
              REDIS_REPLICATION_MODE: master
            envFrom:
              - secretRef:
                  name: *secret
            command: ["redis-server", "--requirepass", "$(REDIS_PASSWORD)"]

      ml:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v1.93.3
            envFrom:
              - secretRef:
                  name: *secret
              - configMapRef:
                  name: *cm
            resources:
              requests:
                memory: 2150M
              limits:
                memory: 8Gi

      micro:
        type: deployment
        replicas: 2
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.93.3
            args: ["start-microservices.sh"]
            envFrom:
              - secretRef:
                  name: *secret
              - configMapRef:
                  name: *cm
            resources:
              requests:
                memory: 512M
              limits:
                memory: 1056M

    service:
      main:
        ports:
          http:
            port: 3001
      ml:
        controller: ml
        ports:
          http:
            port: 3003
      redis:
        controller: redis
        ports:
          http:
            port: 6379
    ingress:
      main:
        enabled: true
        className: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "movie-play"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host "immich.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: "immich-tls"

    persistence:
      library:
        enabled: true
        existingClaim: nfs-immich-pvc
        globalMounts:
          - path: /usr/src/app/upload
      config:
        enabled: false
