apiVersion: v1
kind: Secret
metadata:
    name: secret-immich
    namespace: media
stringData:
    DB_DATABASE_NAME: ENC[AES256_GCM,data:Wpv7F7/Z,iv:D2doswiar/sUF8wBVCwbqsne1IakLNPTF/rzeloNttg=,tag:s3khkpTomn21PdLPDwuBcw==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:F0jPEEuG6fbh5SR1ZBN4jX2oJVTifotssha5hGHtOBMiySsj7bGWLrQO4eWw,iv:uI0XSaYdgPUVr4F7WqZIBiGUF3NMzqEK55fRcpVs64o=,tag:4t8rVa2G6AdoZ9o5mq8bOQ==,type:str]
    REDIS_HOSTNAME: ENC[AES256_GCM,data:SUYQ7nDSYOalC9LYxdqVZibfAwF2Z7ecmnmEgZh6Pj0JtEO6,iv:NbQ/I5U/SiEk38LLGp+x56d8T2wIdUhApNpsfslFM9Q=,tag:WBhRhny3uShQv8iOA1bVlA==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:PjlsxSOsxsXZZwufbGlytZIX+zulnfGH6KXwX/nt13uXmw==,iv:D4ZhXh8RQiK/3yuXdX6a/7SFwkzn0GJqMhRe9ptODTU=,tag:m6KfHD0WsQ6O+8pRpLo3qA==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:bKH1nJq7ptx00emLSKSlcuiX5ZoKsfmVL0egzMDQcA==,iv:/sl08Up0z8tXBP0lNBJPoAHJK5Q/Px7aZv+Z1YfWvlM=,tag:kWp+PFuCFVgxHzGpk2opzA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:4z73PW3v6l/o74lw49zExd+exe74aFkgkddQqTtTwA==,iv:hZXHdN+kCz3pSFBNJqRsnteDAj2I30phs+//0ClbfJU=,tag:J9VPXv1lsfZFliT0KUj3bg==,type:str]
    #ENC[AES256_GCM,data:rnGav/C/oQCVmNe5VMY4utJsX3OxKR+cl6q/N7ughQ==,iv:sHxj00j2FJ4VBTjy2iLhomUhSgj9OH2alSo/9xmRYiM=,tag:gMi3/k0+2pjbVxxX57xvyA==,type:comment]
    #ENC[AES256_GCM,data:o5yYki43O15axH+58tUGaQg8V1pnVoUrcnwWiw5eC1DCeLcnjJmyw7jhzlSV,iv:rujqDzDza08/vi7icT+w3Ndxvp1n1ZLixHXNZNYj6c0=,tag:fYOdI+MUp5HWIJq24pka/Q==,type:comment]
    #ENC[AES256_GCM,data:mS3HrSItIBQOE/AZLe0=,iv:pniOJi5KI0KyZg0ZfbsZ1nSf3TidDVG8rVM1cmKbaUo=,tag:g8dnRlyBhtLVVaUeEJoFsw==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:J+ExwIvb,iv:3SXtJHhLT7mmfGxg9E7wikqC/4npMRbF/4OhEJykRhI=,tag:OuwT4MGrgFIoRXcaBiI3GA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:ceY8mqAvuyXuhUHbRpshZhUPx/mxhSlgLPkwIrpTLB7y8MFqIfgMc+uekp0/,iv:Qbiq1b61LliKIsSba8Ln/qStDASS3Or5BEDr/9cGdco=,tag:EHhpp3Nrb3g1Wi++b5Z1BQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:3vKJWMJhCoxwESaWnxJPcX8hIzy4BrWtUuVNDugp0g==,iv:O4+13vpUGQXRyNVYEaadx5wfI+bJMC1k7UfHx/u5AME=,tag:Qkyi6kgxPkNRiNAK8D3bWA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:T6CBLadbpnlWnZOpxfEFGevV+m0eXWAfz+4/7lWQEQ==,iv:n//A8qyIJoMcv73WektkCn6hRCNGIcqE844vAfAlvi8=,tag:aETDeshHh8MVKfgJ2J4vWA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:wCQdWKLwIDBbnTSDq+BtlsJ3iGhy2quSys9KSpXiYUgZ2LsScw==,iv:3eWCyf+DgRr/pHpiwvrBoKWh8ZhLlhPCu//vWpk8lsI=,tag:jEaBP5V9yLSIC4MReu3bJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age146q3v4ent838axktd2jq49v48pctuhhmv49843wnmlygv8r2uyysjs8mfd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WUNQWmE5WEtKWnlaUEc3
            R1FxNU9WdlFtcWg4b282NEF0YmJROVJ0amtNClpPeXBodXRkWndielhmbk1PSXAx
            QjdxRW1DSUVWcGZILzdCZUprVkRRV28KLS0tIDA5emF1ank4YXc4SFZ4VGlQZWlZ
            cmNOTUxUTGRRVUNsV0hmWHdTaXJGZlUKGquIJKH4wtr0jaaUWMNDP2XvSBRyuYJK
            iMMeR303TZUa+WGi3fDE7w+EW0f3vcgaz9FwJeenh6k3kl2shCYZPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-22T17:36:19Z"
    mac: ENC[AES256_GCM,data:eytW7YdX7vXyaOJ7h99Yu5uVcfiC22FtT1uJvCXjguVv/RQjXBAH+CMfjZkRe2D8Y8YBJ/eS4/UY5DAJ/243gD1cnWi6zmviwPMsUJCOHuVHANO8Rj3PtGP9TVtBFDBNSvgme6B/Ifo99mxHhIz2DMAPgBD26q1lbGc58nDeyvg=,iv:NUlvOajAYTjnNJB1dnDzTsu5Qlilr0M1uqPc1IKVWk8=,tag:AJEp0nDc87Ojc1BZcbUycQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
