---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: botkube
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: datasource=github-releases depName=kubeshop/botkube
      chart: botkube
      version: v0.12.4
      sourceRef:
        kind: HelmRepository
        name: infracloudio-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: kubeshop/botkube
      tag: v1.11.0
    serviceMonitor:
      enabled: true
    logLevel: debug
    communications:
      discord:
        enabled: true
        token: ${SECRET_BOTKUBE_DISCORD_TOKEN}
        botid: "941498306876555395"
        channel: "650761898463330357"
    config:
      recommendations: true
      ssl:
        enabled: false
      settings:
        kubectl:
          enabled: true
          restrictAccess: false
      resources:
        - name: velero.io/v1/backups
          namespaces:
            include:
              - all
          events:
            - all
          updateSetting:
            includeDiff: true
            fields:
              - status.phase
        - name: velero.io/v1/restores
          namespaces:
            include:
              - all
          events:
            - all
          updateSetting:
            includeDiff: true
            fields:
              - status.phase

        - name: v1/services
          namespaces:
            include:
              - default
              - home
              - kube-system
              - media
              - monitoring
              - networking
          events:
            - create
            - delete
            - error
        - name: apps/v1/deployments
          namespaces:
            include:
              - default
              - home
              - kube-system
              - media
              - monitoring
              - networking
          events:
            - create
            - update
            - delete
            - error
        - name: apps/v1/statefulsets
          namespaces:
            include:
              - default
              - home
              - kube-system
              - media
              - monitoring
              - networking
          events:
            - create
            - update
            - delete
            - error
        - name: network.k8s.io/v1beta1/ingresses
          namespaces:
            include:
              - default
              - home
              - kube-system
              - media
              - monitoring
              - networking
          events:
            - create
            - delete
            - error
        - name: v1/nodes
          namespaces:
            include:
              - default
              - home
              - kube-system
              - media
              - monitoring
              - networking
          events:
            - create
            - delete
            - error
        - name: v1/namespaces
          namespaces:
            include:
              - default
              - home
              - kube-system
              - media
              - monitoring
              - networking
          events:
            - create
            - delete
            - error
        - name: v1/persistentvolumes
          namespaces:
            include:
              - default
              - home
              - kube-system
              - media
              - monitoring
              - networking
          events:
            - create
            - delete
            - error
        - name: v1/persistentvolumeclaims
          namespaces:
            include:
              - default
              - home
              - kube-system
              - media
              - monitoring
              - networking
          events:
            - create
            - delete
            - error
        - name: v1/configmaps
          namespaces:
            include:
              - default
              - home
              - kube-system
              - media
              - monitoring
              - networking
          events:
            - create
            - delete
            - error
        - name: apps/v1/daemonsets
          namespaces:
            include:
              - default
              - home
              - kube-system
              - media
              - monitoring
              - networking
          events:
            - create
            - delete
            - error
        - name: batch/v1/jobs
          namespaces:
            include:
              - default
              - home
              - kube-system
              - media
              - monitoring
              - networking
          events:
            - update
            - error

    resources:
      requests:
        cpu: 75m
        memory: 64Mi
      limits:
        memory: 128Mi
