---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: botkube
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://infracloudio.github.io/charts
      chart: botkube
      version: v0.12.4
      sourceRef:
        kind: HelmRepository
        name: infracloudio-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: infracloudio/botkube
      tag: v0.12.3
      pullPolicy: Always
    # logLevel: debug
    extraAnnotations:
      secret.reloader.stakater.com/reload: botkube-configmap

    serviceMonitor:
      enabled: true
    config:
      communications:
        discord:
          enabled: true
          notiftype: short
      resources:
        - name: v1/services
          namespaces:
            include:
              - default
              - home
              - kube-system
              - media
              - monitoring
              - networking
          events:
            - create
            - delete
            - error
        - name: apps/v1/deployments
          namespaces:
            include:
              - default
              - home
              - kube-system
              - media
              - monitoring
              - networking
          events:
            - create
            - update
            - delete
            - error
        - name: apps/v1/statefulsets
          namespaces:
            include:
              - default
              - home
              - kube-system
              - media
              - monitoring
              - networking
          events:
            - create
            - update
            - delete
            - error
        - name: network.k8s.io/v1beta1/ingresses
          namespaces:
            include:
              - default
              - home
              - kube-system
              - media
              - monitoring
              - networking
          events:
            - create
            - delete
            - error
        - name: v1/nodes
          namespaces:
            include:
              - default
              - home
              - kube-system
              - media
              - monitoring
              - networking
          events:
            - create
            - delete
            - error
        - name: v1/namespaces
          namespaces:
            include:
              - default
              - home
              - kube-system
              - media
              - monitoring
              - networking
          events:
            - create
            - delete
            - error
        - name: v1/persistentvolumes
          namespaces:
            include:
              - default
              - home
              - kube-system
              - media
              - monitoring
              - networking
          events:
            - create
            - delete
            - error
        - name: v1/persistentvolumeclaims
          namespaces:
            include:
              - default
              - home
              - kube-system
              - media
              - monitoring
              - networking
          events:
            - create
            - delete
            - error
        - name: v1/configmaps
          namespaces:
            include:
              - default
              - home
              - kube-system
              - media
              - monitoring
              - networking
          events:
            - create
            - delete
            - error
        - name: apps/v1/daemonsets
          namespaces:
            include:
              - default
              - home
              - kube-system
              - media
              - monitoring
              - networking
          events:
            - create
            - delete
            - error
        - name: batch/v1/jobs
          namespaces:
            include:
              - default
              - home
              - kube-system
              - media
              - monitoring
              - networking
          events:
            - update
            - error
        - name: rbac.authorization.k8s.io/v1/rolebindings
          namespaces:
            include:
              - default
              - home
              - kube-system
              - media
              - monitoring
              - networking
          events:
            - create
            - delete
            - error
        - name: rbac.authorization.k8s.io/v1/clusterrolebindings
          namespaces:
            include:
              - default
              - home
              - kube-system
              - media
              - monitoring
              - networking
          events:
            - create
            - delete
            - error
        - name: rbac.authorization.k8s.io/v1/clusterroles
          namespaces:
            include:
              - default
              - home
              - kube-system
              - media
              - monitoring
              - networking
          events:
            - create
            - delete
            - error

    resources:
      requests:
        cpu: 75m
        memory: 64Mi
      limits:
        memory: 128Mi

    valuesFrom:
      - kind: Secret
        name: botkube-discord
        optional: false
        valuesKey: discord-token
        targetPath: communications.discord.token
      - kind: Secret
        name: botkube-discord
        optional: false
        valuesKey: discord-botid
        targetPath: communications.discord.botid
      - kind: Secret
        name: botkube-discord
        optional:
        valuesKey: discord-channel
        targetPath: communications.discord.channel
