---
name: Scan Containers

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "cluster/**.yaml"
      - "provision/ansible/**.yml.j2"
      - "provision/ansible/**.yaml.j2"

jobs:
  detect-file-changes:
    name: Detect File Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        id: filter
        with:
          list-files: json
          filters: |
            yaml:
              - added|modified: "**.yaml"
              - added|modified: "**.yml"
              - added|modified: "**.yaml.j2"
              - added|modified: "**.yml.j2"
    outputs:
      yaml_files: ${{ steps.filter.outputs.yaml_files }}

  detect-containers:
    name: Detect Containers
    runs-on: ubuntu-latest
    needs: detect-file-changes
    strategy:
      matrix:
        file: ${{ fromJSON(needs.detect-file-changes.outputs.yaml_files) }}
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Install Jo
        run: |
          sudo apt-get install jo
      - name: Detect Containers in Files
        id: containers
        run: |
          chmod +x .github/scripts/container-parser.sh
          containers=$(.github/scripts/container-parser.sh --file "${{ matrix.file }}")
          echo "${containers}"
          echo ::set-output name=containers::${containers}
    outputs:
      containers: ${{ steps.containers.outputs.containers }}

  scan-containers:
    name: Scan Containers
    runs-on: ubuntu-latest
    needs: detect-containers
    strategy:
      matrix: ${{ fromJSON(needs.detect-containers.outputs.containers) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Scan Container
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        with:
          image-ref: ${{ matrix.containers }}
          vuln-type: os,library
          severity: CRITICAL,HIGH
          format: template
          template: "@/contrib/sarif.tpl"
          output: trivy-results.sarif
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@d198d2fabf39a7f36b5ce57ce70d4942944f006e # v3
        with:
          sarif_file: trivy-results.sarif
