---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: docker-registry
  namespace: utility
spec:
  interval: 5m
  chart:
    spec:
      chart: docker-registry
      version: "2.1.0"
      sourceRef:
        kind: HelmRepository
        name: twuni-charts
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: registry
      tag: 2.7.1
    ingress:
      enabled: true
      className: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      path: /
      hosts:
        - "docker-registry.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - "docker-registry.${SECRET_DOMAIN}"

    storage: filesystem

    persistence:
      enabled: true
      size: "10Gi"
      storageClass: "ceph-block"

    proxy:
      enabled: true
      remoteurl: https://registry-1.docker.io
      username: "${SECRET_DOCKERHUB_USER}"
      password: "${SECRET_DOCKERHUB_PASSWORD}"

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
